<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Berikutnya Daftar</name>
   <tag></tag>
   <elementGuidId>bba946d0-d055-4f60-a74f-60723df52f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_submit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '/appData/action' and @id = 'paypalAccountData_submit' and (text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paypalAccountData_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcccf0bb-b3a1-4c84-ac33-41584ce2643e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-ylhy9c-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>9f53da61-4b0f-4f43-b900-88b9a7019ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.5.4</value>
      <webElementGuid>37d1cc79-5230-4016-bbea-73edb0b02bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/appData/action</value>
      <webElementGuid>b5f70f81-eaaf-4cfc-b31d-2d1a0ee6b5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_submit</value>
      <webElementGuid>fe6984d8-fc80-4ed7-acde-06dd64fd8ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login_info_phone</value>
      <webElementGuid>e374d1b7-a649-40e2-8342-ed9175a7278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>page_submit</value>
      <webElementGuid>87ae1537-268c-4213-a8e6-74c870c240be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>627531d7-34ec-423b-8783-7ba96eb29971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikutnya</value>
      <webElementGuid>8284196e-4a2f-4567-afba-45b18536d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_submit&quot;)</value>
      <webElementGuid>76b4fe65-4187-4af4-9093-16b62c532931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paypalAccountData_submit']</value>
      <webElementGuid>77c1aead-1c9e-4746-afc5-968dff6acd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div[2]/div/div[2]/div/button</value>
      <webElementGuid>77bcfe9d-5756-41fd-a526-d4656036b56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='k+2@example.com'])[1]/following::button[1]</value>
      <webElementGuid>9aff48a9-46fd-4d7a-9677-89f706cc5fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>3a1027e8-68a8-4159-857f-acb07c25629f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2024 PayPal'])[1]/preceding::button[1]</value>
      <webElementGuid>9b8987e5-d25f-4ced-a8dd-276acc67d4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privasi'])[1]/preceding::button[1]</value>
      <webElementGuid>6adcebbe-1bc1-492d-85f7-393deccfeaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Berikutnya']/parent::*</value>
      <webElementGuid>57835723-8a54-4ec0-b292-e0e6b7c59e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>049a7600-57db-45a6-94f6-bd9e3a193b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '/appData/action' and @id = 'paypalAccountData_submit' and (text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      <webElementGuid>44424191-c643-4899-932c-ab86ee70f549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
