<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact 1</name>
   <tag></tag>
   <elementGuidId>ebae98be-03e9-46da-8476-0ed8d61f0518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-14ec7kq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div/ul/li/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3b7afe7-1d56-4567-befa-0367c9cc93af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-14ec7kq</value>
      <webElementGuid>abe359d4-3a65-4f27-a3c1-8a347efcfc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[1]/div[@class=&quot;css-18v44rk&quot;]/div[1]/div[@class=&quot;css-124g4oa transferPage row&quot;]/form[@class=&quot;css-1m4rlv3 col-md-8&quot;]/div[@class=&quot;css-1kvk3dd&quot;]/div[@class=&quot;css-1cel6f4&quot;]/div[@class=&quot;css-1w2070v&quot;]/ul[1]/li[@class=&quot;css-6sll1x&quot;]/button[@class=&quot;css-1n3hp90&quot;]/div[@class=&quot;css-14ec7kq&quot;]</value>
      <webElementGuid>6952d728-ca87-4fb9-9b54-0b0ed08ca983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div/ul/li/button/div</value>
      <webElementGuid>ce407952-9d84-4506-9940-ed9281b62c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[4]</value>
      <webElementGuid>5761aee8-b954-49aa-b72a-d111a7914532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear search input'])[1]/following::div[4]</value>
      <webElementGuid>a4bc7550-b154-48e3-91f6-a8bb0ef63ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[1]/preceding::div[2]</value>
      <webElementGuid>48c0d583-7b5a-43b5-b45d-399abf350417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage contacts'])[1]/preceding::div[4]</value>
      <webElementGuid>33acd18c-4307-4f80-b2cc-45aa593b3e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>264680ae-3031-4c28-bab3-26a3bcee5198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
