<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description payment</name>
   <tag></tag>
   <elementGuidId>d6005ef7-91e6-4d4e-9c5a-828546d5c97e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noteField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='noteField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ace42233-2dba-4ead-a2f2-f5f0831d629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1p2upr css-1xmckvi-text_input_control-text_body-no_label_text_input_control-label_placeholder_shown_and_not_focused-text_body-text_area_control</value>
      <webElementGuid>4da0079d-b6d4-4acf-b316-3916e4bc8b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noteField</value>
      <webElementGuid>82d339f0-b744-4a10-8f88-cc9fd9f5c0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44d7b375-4429-45d4-8eac-c682d73b6e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What’s this for?</value>
      <webElementGuid>0c049154-e335-44b2-b140-841586ec9037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>text-area_5.5.4</value>
      <webElementGuid>91c93e5f-82e8-4c87-bd75-f2f96b93cf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>v2</value>
      <webElementGuid>c66faf00-d015-457f-b43e-2b542c847f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>note-field</value>
      <webElementGuid>638766d8-7365-4796-8404-93c8f75ddd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e48c9f2-bc57-4df0-b968-7412e29b7871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noteField&quot;)</value>
      <webElementGuid>a09bdb2e-1dfb-4ac6-afd4-f0b452a12274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='noteField']</value>
      <webElementGuid>544c40c8-32eb-4a94-8093-19147fc64ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preview-wrapper']/div[3]/div/div/div/textarea</value>
      <webElementGuid>850c8336-2352-4762-bf18-d7dd64baa51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>584ead88-142f-4362-a18b-20c65e32d1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'noteField' and @placeholder = 'What’s this for?']</value>
      <webElementGuid>83f5f45a-0d3a-4316-9132-155fcd73634f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
