<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manage contacts</name>
   <tag></tag>
   <elementGuidId>ce14ae06-0d55-49a2-b0d1-0fbb1c3ca3a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-18m6lt0-links_base-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b274b5bd-b703-443d-9c0b-2e6afe730e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18m6lt0-links_base-text_body_strong</value>
      <webElementGuid>ee1cac28-68de-4a06-ad9b-39216b80d30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>045fd689-67bc-4a1c-aa2f-31dd4751ef2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start</value>
      <webElementGuid>afc881b8-5444-4465-9088-81a9b23ed59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename2</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start:node::</value>
      <webElementGuid>fb498f80-e73d-4c92-8776-1a4595cbf2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer/homepage/contact-list</value>
      <webElementGuid>d6fb8a60-0fe3-4d13-8a03-e9a8a9bccdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3e7ec81-376e-446d-9042-797dab68cfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage contacts</value>
      <webElementGuid>8b1a3992-0c93-4c50-a437-a606cb9af674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[1]/div[@class=&quot;css-18v44rk&quot;]/div[1]/div[@class=&quot;css-124g4oa transferPage row&quot;]/form[@class=&quot;css-1m4rlv3 col-md-8&quot;]/div[@class=&quot;css-1kvk3dd&quot;]/div[@class=&quot;css-1cel6f4&quot;]/div[@class=&quot;css-1gfmy99&quot;]/a[@class=&quot;css-18m6lt0-links_base-text_body_strong&quot;]</value>
      <webElementGuid>f0d429f3-282d-4b45-a459-7a65f06d4a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div[2]/a</value>
      <webElementGuid>3a3cbc9e-7065-4d3f-b0fd-1d87df9f0b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage contacts')]</value>
      <webElementGuid>9f868ef1-4747-4bb3-8729-475329c2bc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[1]/following::a[1]</value>
      <webElementGuid>7283e19f-c54b-4360-b382-8e2a9889f591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>257bfefb-8ed9-4771-85ae-e2eb456897f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More ways to send'])[1]/preceding::a[1]</value>
      <webElementGuid>62f63546-3368-4093-afd6-2669ba52ffb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More ways to send'])[2]/preceding::a[1]</value>
      <webElementGuid>ecbdc8ee-4a1c-4bc0-a77f-8187b7bc0d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage contacts']/parent::*</value>
      <webElementGuid>16d7b80a-54b3-4ba5-a200-8fb9e0664359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/transfer/homepage/contact-list')]</value>
      <webElementGuid>f2fdfeb4-8d55-48e5-b9d3-9aee6e5d6221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>3fbd846c-f9fa-4145-b7e5-d9f578503653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer/homepage/contact-list' and (text() = 'Manage contacts' or . = 'Manage contacts')]</value>
      <webElementGuid>7106ccac-ab5d-4dab-b2c2-dcc5b0409de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
