<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pay Test Store</name>
   <tag></tag>
   <elementGuidId>dea19d34-9fc7-46d7-84df-a857b151ae2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-e8m3n2-avatar_base-size_lg-text_heading_lg-size_md-text_heading_sm-merchant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div/ul/li/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6f01901-9a28-436a-a7b1-ebe93c00892b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-e8m3n2-avatar_base-size_lg-text_heading_lg-size_md-text_heading_sm-merchant</value>
      <webElementGuid>fbb4482a-7abb-41f1-986f-2abc3701a691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>avatar_4.5.8</value>
      <webElementGuid>72501fa9-7bf0-4c82-b5b1-8233e806d7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7a6a2d2-fef4-40b2-985a-8547046625b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[1]/div[@class=&quot;css-18v44rk&quot;]/div[1]/div[@class=&quot;css-124g4oa transferPage row&quot;]/form[@class=&quot;css-1m4rlv3 col-md-8&quot;]/div[@class=&quot;css-1kvk3dd&quot;]/div[@class=&quot;css-1cel6f4&quot;]/div[@class=&quot;css-1w2070v&quot;]/ul[1]/li[@class=&quot;css-6sll1x&quot;]/button[@class=&quot;css-1n3hp90&quot;]/div[@class=&quot;css-14ec7kq&quot;]/div[@class=&quot;css-e8m3n2-avatar_base-size_lg-text_heading_lg-size_md-text_heading_sm-merchant&quot;]</value>
      <webElementGuid>acf2a809-d29d-494b-877a-7293313fe25c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/form/div[2]/div/div/ul/li/button/div/div</value>
      <webElementGuid>2b4f9323-3bea-45de-b924-0d46caaa3b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[5]</value>
      <webElementGuid>c796b106-04ce-40d9-9fce-753111a2e336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, @username, email, or mobile'])[1]/following::div[5]</value>
      <webElementGuid>96d39cbc-c38d-48be-a6cc-82956883565f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[1]/preceding::div[1]</value>
      <webElementGuid>900540b2-5ef8-4cab-a537-781b0c3dcd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John'])[1]/preceding::div[5]</value>
      <webElementGuid>c2827ba5-3f11-4d30-a9ee-3502dbf12dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div</value>
      <webElementGuid>d16af461-cca5-47bb-b5ee-6a8679b0bef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
