<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send</name>
   <tag></tag>
   <elementGuidId>c818ac73-fca8-4319-893a-fa471263fcb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-2swc02.css-1mvakau-button_base-text_button_lg-btn_full_width</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/form/div[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4874473c-5da0-40cd-b86b-ae65ef18f072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>853c1004-de78-4ba3-bfc3-1f24b7a540a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-2swc02 css-1mvakau-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>814db441-5d2f-4b6d-aca0-c70d0a4f623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.1</value>
      <webElementGuid>e1f097c2-ceaf-4764-aced-6fb0d8f5e7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>4479f73f-ffa9-48de-a3cb-956334d1e898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>22fc5724-ddbf-40df-9a72-eadc80e8a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/form[@class=&quot;css-mv64iv&quot;]/div[@class=&quot;css-1dd53x1&quot;]/button[@class=&quot;css-2swc02 css-1mvakau-button_base-text_button_lg-btn_full_width&quot;]</value>
      <webElementGuid>6353bc40-baaa-4aea-bfe1-333f0ffc0c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/form/div[4]/button</value>
      <webElementGuid>d6d7c900-5de3-43a9-af82-a05382b70f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user agreement'])[1]/following::button[1]</value>
      <webElementGuid>805715f1-9b10-4ede-b752-a141e6dc6ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>cf9fc814-3164-4e8b-a4e4-7489f0e80397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::button[2]</value>
      <webElementGuid>b5c030f7-0b87-4454-b8f4-28d96967d65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>497805f3-4654-477c-9984-3781d5b6b2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>93708fd2-9845-41d9-8f3c-a7b217bd6620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>940fca2f-b8a9-44ba-9db7-c0bd65b96842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
