<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contacts</name>
   <tag></tag>
   <elementGuidId>8c7d4e32-ac78-4b83-a838-bcb82b72d820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-nav-tabs-tab3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='secondary-nav-tabs-tab3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb02b189-165a-4ea1-98c0-a5b03b133981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>143042fc-3170-41a8-908d-b53da33231a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-nav-tabs-tab3</value>
      <webElementGuid>caea683a-84bf-4650-8dbb-9a2a9a6456b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-l7gpwq-tabs_btn-text_body</value>
      <webElementGuid>806c5660-791f-4f0f-82a1-7b3e0877c201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>secondary-nav-tab-2</value>
      <webElementGuid>166babf6-59b6-4e87-b07d-3515c9642ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c4b7ef5-ed38-4f54-8a7a-3a1279496b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d0dc2c34-797a-4902-8393-62a716d88ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f0f8ecc-cef0-4de9-85e4-4e1c6158e93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4ee32a6b-2bf9-44c3-baaf-196eaf9d752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>main:p2p:tab-contacts</value>
      <webElementGuid>268b5a1b-a9cd-4be2-870a-633aae26007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:p2p:tab-contacts</value>
      <webElementGuid>3db322a2-b767-48c9-bfbb-4f317f266253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename2</name>
      <type>Main</type>
      <value>main:p2p:tab-contacts:node::</value>
      <webElementGuid>ca46e046-7fd1-4f08-873f-c082bbff6e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagename</name>
      <type>Main</type>
      <value>main:p2p:tab-contacts:node::</value>
      <webElementGuid>380b02ca-688c-42c1-ad2c-ac01dc2a973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagegroup</name>
      <type>Main</type>
      <value>main:p2p:tab-contacts</value>
      <webElementGuid>3402fb6b-42c2-48af-a5e0-a3e11f8764f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extra</name>
      <type>Main</type>
      <value>{&quot;linkname&quot;:&quot;linkTabContacts&quot;}</value>
      <webElementGuid>b7ac6c9a-ff00-445b-af83-728dc160c092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ec93516-474c-4825-bc53-c757c5dc1298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-text</name>
      <type>Main</type>
      <value>Contacts</value>
      <webElementGuid>5f5ddc56-b1c3-4db9-8b8e-dd188ee556a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45f38a4b-849f-4105-ad34-ca627a837365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacts</value>
      <webElementGuid>6af165f4-3987-4709-95d1-c330db4298ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-nav-tabs-tab3&quot;)</value>
      <webElementGuid>7252b74a-a3b4-47e3-adfe-a1452f6e7bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='secondary-nav-tabs-tab3']</value>
      <webElementGuid>76e37164-5b60-4a19-a5a1-47b4882372d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary-nav-tabs-tabs']/button[3]</value>
      <webElementGuid>550bf469-87cb-406c-9b3a-d91d487dccce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/following::button[1]</value>
      <webElementGuid>7a374608-0c0c-497f-b32c-57d4674f935e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::button[2]</value>
      <webElementGuid>80b73a05-e25b-4e00-822d-2a2781d5d63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::button[1]</value>
      <webElementGuid>3d675a46-c1eb-4384-ba4e-98b682a6ac13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll left'])[1]/preceding::button[2]</value>
      <webElementGuid>e4654153-babd-4069-b04d-8cf0585cc1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contacts']/parent::*</value>
      <webElementGuid>903f7625-d0ce-472c-99e2-15238d6f66aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>ff8c5972-1052-4414-913f-e79e4a20abda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'secondary-nav-tabs-tab3' and @type = 'button' and (text() = 'Contacts' or . = 'Contacts')]</value>
      <webElementGuid>4b2887ed-a46f-4c8f-8f8b-9ace18782437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
