<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>More</name>
   <tag></tag>
   <elementGuidId>90a856db-aaf9-450f-b119-b88cc326c709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-nav-tabs-tab4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='secondary-nav-tabs-tab4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>203b37fe-20eb-45b3-9936-23e8c1e48d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9cd0edf0-6d58-4163-ae6d-cce9697e49b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-nav-tabs-tab4</value>
      <webElementGuid>935b22f5-e838-47a5-a247-585a96c828f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-l7gpwq-tabs_btn-text_body</value>
      <webElementGuid>18315cb4-c9b8-4975-8644-cd4191591996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>secondary-nav-tab-3</value>
      <webElementGuid>f14566f2-8d8c-41ef-8b2c-ce5bf037f153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fec9c599-0078-4c18-8d18-c0ad7811fab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa2d955a-b335-4d11-ba07-ab6f6666cc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ef0b98a-0a21-4cb2-ae1a-70f900f570a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d3db1006-43a2-4695-a9b2-f002c1359aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>main:p2p:tab-more</value>
      <webElementGuid>a3980a30-b988-4dae-9fe3-f459e912d5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:p2p:tab-more</value>
      <webElementGuid>8d827fcc-9f47-4e17-b8ed-abdd40f572ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename2</name>
      <type>Main</type>
      <value>main:p2p:tab-more:node::</value>
      <webElementGuid>f63d5f04-027a-403e-ae47-4b56efb7a96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagename</name>
      <type>Main</type>
      <value>main:p2p:tab-more:node::</value>
      <webElementGuid>0cf79be3-595e-48a2-a8fb-6f5254714e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagegroup</name>
      <type>Main</type>
      <value>main:p2p:tab-more</value>
      <webElementGuid>12e9d552-4404-49f2-ad00-ceb5a3206fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extra</name>
      <type>Main</type>
      <value>{&quot;linkname&quot;:&quot;linkTabMore&quot;}</value>
      <webElementGuid>0566ed60-0d81-40dc-9d1d-588c87955c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c29a34b0-e68f-4f69-b9b9-6cf8da96fae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-text</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>7287c292-4d24-4a95-a76b-948abd170529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da56ec8b-19fd-4f2c-9a07-33f1f8b98dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More</value>
      <webElementGuid>53d0abf5-2253-47d5-ac6c-9cf6594af027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-nav-tabs-tab4&quot;)</value>
      <webElementGuid>d71c7d92-75d0-45a3-ad25-a6211e5fa4a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='secondary-nav-tabs-tab4']</value>
      <webElementGuid>b4d7400e-9b53-4a16-aeb5-a28001eca9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary-nav-tabs-tabs']/button[4]</value>
      <webElementGuid>28549251-5980-481c-ab3c-09bb65d9886f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::button[1]</value>
      <webElementGuid>3eb68f17-8d92-4a8c-a878-257b4d2e7222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/following::button[2]</value>
      <webElementGuid>a7687a65-e9eb-4208-8038-5bf396137cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll left'])[1]/preceding::button[1]</value>
      <webElementGuid>e4e9523e-df80-4111-aa8e-662a78b06836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll right'])[1]/preceding::button[2]</value>
      <webElementGuid>862fc3b0-65d7-40b9-9698-ba149fbb8f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='More']/parent::*</value>
      <webElementGuid>813fddc2-d82b-4b0e-8fa9-33b35da3355a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>117a7eff-a959-4a9a-a98e-2cdc1da01f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'secondary-nav-tabs-tab4' and @type = 'button' and (text() = 'More' or . = 'More')]</value>
      <webElementGuid>c829d4a7-71bc-4b85-bfc6-6da3302a18a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
