<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Request</name>
   <tag></tag>
   <elementGuidId>622e2248-ed08-4b70-9039-91483e4569f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-nav-tabs-tab2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='secondary-nav-tabs-tab2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79b089ee-6307-41bc-a5b2-8231307c9b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4da8336-c0a4-409c-860f-131899eec5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-nav-tabs-tab2</value>
      <webElementGuid>6800c527-c074-4ece-8f9d-a29265130846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-l7gpwq-tabs_btn-text_body</value>
      <webElementGuid>711c9809-af4a-4923-9369-4ee73feeebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>secondary-nav-tab-1</value>
      <webElementGuid>3e84fcde-682e-4fd2-824e-736dc46f4d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1a528e9-2db4-489c-a907-cb556f9035f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3730cc41-1579-44ae-93cd-2b2ef5297e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9aec011-4415-4aab-8cf5-1f76c4404da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6f80227e-6469-4f28-8b12-28f36dba6398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>main:p2p:tab-request</value>
      <webElementGuid>18a66dc5-0b18-4a03-a05f-0021d812f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:p2p:tab-request::start</value>
      <webElementGuid>e8ed1c6f-12f4-4b7d-846b-10d1adc7230b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename2</name>
      <type>Main</type>
      <value>main:p2p:tab-request::start:node::</value>
      <webElementGuid>786d4b06-a82b-4279-9d5d-4e178156b35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagename</name>
      <type>Main</type>
      <value>main:p2p:tab-request::start:node::</value>
      <webElementGuid>757961ce-9cc6-402d-80a4-3a0637b74696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagegroup</name>
      <type>Main</type>
      <value>main:p2p:tab-request::start</value>
      <webElementGuid>8361caa8-cfaa-4ea1-a984-c08128e828ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extra</name>
      <type>Main</type>
      <value>{&quot;linkname&quot;:&quot;linkTabRequest&quot;}</value>
      <webElementGuid>bc99e712-ddf3-4465-b28b-ce417ab09040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52fb33b1-469f-49ad-a36a-9699d383204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>2447a4c0-4a51-48ba-b549-c801f7e9515d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0637b140-0ebf-488b-9e23-35b032250bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>c84f2472-fdd0-480c-a2bb-ce710d088758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-nav-tabs-tab2&quot;)</value>
      <webElementGuid>81dbf00d-612a-410c-bfac-2257f5f998d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='secondary-nav-tabs-tab2']</value>
      <webElementGuid>3c45ac8c-5885-4aa3-80c5-7bc55dc83f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary-nav-tabs-tabs']/button[2]</value>
      <webElementGuid>714eb364-fa77-4f02-9735-6ef0a6b97dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::button[1]</value>
      <webElementGuid>ddc90c95-1c73-43c0-8680-f45b5542e70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Messages'])[2]/following::button[2]</value>
      <webElementGuid>aa352654-1eae-4939-8753-a00774cbd8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::button[1]</value>
      <webElementGuid>99b2407f-cc9c-4aba-a896-e3409ab35ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::button[2]</value>
      <webElementGuid>6ded6b22-92a7-401d-8438-c0b41d1253e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request']/parent::*</value>
      <webElementGuid>f09b190d-f61c-48a8-8329-984a955a2ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/button[2]</value>
      <webElementGuid>96dba53e-4deb-44e2-a4f8-f401d0d82bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'secondary-nav-tabs-tab2' and @type = 'button' and (text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>4bbab343-20ab-4d05-8e32-9828c1458d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
