<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send</name>
   <tag></tag>
   <elementGuidId>6ecfcf94-b9a6-4dcf-b8c9-b1f8a95e1134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-nav-tabs-tab1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='secondary-nav-tabs-tab1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f646baf-c155-44c7-a0d4-3c0da9d6cf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e208c2bc-b68a-49ca-a818-02dc3f3682b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-nav-tabs-tab1</value>
      <webElementGuid>ba4474d9-3be7-4f2b-abdf-dc4f2a13963b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-mdnpq8-tabs_btn-text_body-tab_selected</value>
      <webElementGuid>f12af5e8-1075-4666-af44-bce7a94a49f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>secondary-nav-tab-0</value>
      <webElementGuid>9b2580fe-ab40-4088-9ca5-666f84ab028b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ca2b377-9ed3-4f34-bf2a-9e266ed9e5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4cc9d27-0dfa-42b4-a0c7-41ce442e2c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7134450-0292-440a-8679-d74cb78a8e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4313af5d-e200-4171-a40e-e3a9ec340323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>main:p2p:tab-send</value>
      <webElementGuid>f204d163-dd09-4df8-b9e5-26ca42b46b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start</value>
      <webElementGuid>5adf5579-b2ca-47b2-86a5-dd49289fd820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename2</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start:node::</value>
      <webElementGuid>45e494db-1e46-4f5b-8414-229001ca5213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagename</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start:node::</value>
      <webElementGuid>0bb32211-a998-43b7-b427-2cb5596819f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextpagegroup</name>
      <type>Main</type>
      <value>main:p2p:tab-send::start</value>
      <webElementGuid>4994bc6a-c93a-45a6-93fa-d4c232a912ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extra</name>
      <type>Main</type>
      <value>{&quot;linkname&quot;:&quot;linkTabSend&quot;}</value>
      <webElementGuid>4de640f9-5cf0-49b0-b6ec-12c8922519d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55181c4d-6884-489f-a267-1b76b133330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>f14875d8-3fca-4c77-ae64-4be2c639009d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>01fc2556-7c70-4ec7-a913-1ae4ec37b8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>b13799eb-103b-4aa0-af21-47dc6bcc5718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-nav-tabs-tab1&quot;)</value>
      <webElementGuid>594cd5be-551c-408d-bd2e-d8f903961598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='secondary-nav-tabs-tab1']</value>
      <webElementGuid>d5339fbc-6e9a-4fce-9d59-26eacdf0b7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondary-nav-tabs-tabs']/button</value>
      <webElementGuid>e0533c1b-b1fb-4d6a-a668-76dbc8c6e6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Messages'])[2]/following::button[1]</value>
      <webElementGuid>9fa64951-a3d2-4b8c-addf-09a292cefd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have no new messages.'])[2]/following::button[1]</value>
      <webElementGuid>c91016ef-a943-4c4f-81d2-96ae568ac831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/preceding::button[1]</value>
      <webElementGuid>e7bd650b-99e3-485f-a662-458211adeaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::button[2]</value>
      <webElementGuid>5445c2c5-935b-4e9b-9eaa-ace6ac12c9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>fc3699b9-9ab2-4b0a-a7ec-7a0ade25bdce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/button</value>
      <webElementGuid>2919d8aa-f18a-406b-9dc5-8e4033942af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'secondary-nav-tabs-tab1' and @type = 'button' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>cf865e98-048d-4284-b5b8-7dccfb733dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
