<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next Send Money</name>
   <tag></tag>
   <elementGuidId>47188c1b-20b3-43d8-8579-ee5675a7de83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-mt8s6t.css-1mvakau-button_base-text_button_lg-btn_full_width</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b13d3ec6-b1ae-48e0-a266-4a5a57c0c843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d986ca4f-37eb-4205-8255-4da906757f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-mt8s6t css-1mvakau-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>60f2381d-aab0-4053-b2b1-9589ea8327c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.1</value>
      <webElementGuid>48b754ac-c169-4bee-bdfd-6d06cd7a9305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>choice-next-button</value>
      <webElementGuid>40415120-1d7b-4c0a-ae34-789dfba18d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>8e1cb7d7-61f7-4abe-aa06-d3ccb121bd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[@class=&quot;_128ph2z&quot;]/div[@class=&quot;css-13o0w14&quot;]/button[@class=&quot;css-mt8s6t css-1mvakau-button_base-text_button_lg-btn_full_width&quot;]</value>
      <webElementGuid>1ffbb9a3-226b-4a69-aaad-3badcc456db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/button</value>
      <webElementGuid>4657feaf-96b1-4cfb-90c9-6544fb63f7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ New Card'])[1]/following::button[1]</value>
      <webElementGuid>9c600a40-ded1-4327-8936-54ed73ac15af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee: 66.218 Rp IDR'])[1]/following::button[2]</value>
      <webElementGuid>843f4150-466c-46d7-9ec8-37007092cdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::button[1]</value>
      <webElementGuid>8ab05169-f797-4d73-8bc1-ba44d36f4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::button[2]</value>
      <webElementGuid>ac0ec1ad-2f27-48e4-9ee8-7cee98e6581a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>d598984f-3425-4b90-ae4d-66c891dc43b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cf2b95f8-7623-4ac6-8ecd-ae9a8a8c59f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>6f618e29-1c50-4155-bd79-0f2ec7f20267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
