<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forget password</name>
   <tag></tag>
   <elementGuidId>0f079bda-a1f4-4691-9bae-5ad2aa49ada3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>314439fd-7e6e-4ecd-85f7-ed1c04aca570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/authflow/password-recovery/?country.x=ID&amp;locale.x=id_ID&amp;redirectUri=%252Fsignin</value>
      <webElementGuid>bdf46910-995d-4801-8f67-d4749a453562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>405f6aa2-21c7-489a-8e7b-07ff51cd7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recoveryOption forgotPassword </value>
      <webElementGuid>3627fbe9-f171-4039-ab7a-d26a21e8cbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-client-log-action-type</name>
      <type>Main</type>
      <value>clickForgotPasswordLink</value>
      <webElementGuid>c7fd669c-30a8-4aa9-b819-f68a916c6bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>367661d8-9020-4a23-8d36-abcc754bc825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa sandi?</value>
      <webElementGuid>fcb03079-c75f-4f80-bf12-d5cad5ceace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>f1246842-9e1c-4c5b-987d-565a13263719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>04767ed6-db5e-462a-ac64-ea476b8fb1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordSection']/a[2]</value>
      <webElementGuid>69cab951-853a-4e64-b5df-c9aa23e26062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lupa sandi?')]</value>
      <webElementGuid>f85071bb-607b-414d-b51a-6708e71460d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur sandi'])[1]/following::a[1]</value>
      <webElementGuid>8a79df03-2146-49b0-ba1e-ec134dba1828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sembunyikan'])[2]/following::a[2]</value>
      <webElementGuid>672d4104-d925-4b9b-9c90-b8040ffad21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::a[1]</value>
      <webElementGuid>b05003ec-b4b0-4ef3-938c-6ca7ba591b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengalami masalah saat log in?'])[1]/preceding::a[3]</value>
      <webElementGuid>f98d38ae-2654-4918-9b26-05f237d92fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lupa sandi?']/parent::*</value>
      <webElementGuid>9ea2f907-05d3-468d-9f65-ce9c9321a7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/authflow/password-recovery/?country.x=ID&amp;locale.x=id_ID&amp;redirectUri=%252Fsignin')])[2]</value>
      <webElementGuid>707488de-3a96-4582-ba46-0ce0b1994159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>747d0f17-e130-4918-865b-37a03ace56cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/authflow/password-recovery/?country.x=ID&amp;locale.x=id_ID&amp;redirectUri=%252Fsignin' and @id = 'forgotPassword' and (text() = 'Lupa sandi?' or . = 'Lupa sandi?')]</value>
      <webElementGuid>da0c5893-af2d-4079-8c1a-7f9b57fb2908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
