<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sign Up</name>
   <tag></tag>
   <elementGuidId>124bed09-0de7-4b80-b829-ddc2086cf779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='createAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70c74126-01fd-466b-ba10-dd9a1d8db482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0eca6ed-dc32-441a-8f36-5cb66ff6d856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/id/webapps/mpp/account-selection</value>
      <webElementGuid>9305f7fb-e668-48c6-96ff-66ce0df006cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button secondary scTrack:unifiedlogin-click-signup-button</value>
      <webElementGuid>c9063bad-7e7b-49bc-b8c9-6500d76fb7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createAccount</value>
      <webElementGuid>79abff58-682d-4bab-85e7-cd2f8fd33233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>964c55e6-201e-440e-9536-ed7f7e323199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>65281a59-4233-410c-8817-efd1b21b70d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createAccount&quot;)</value>
      <webElementGuid>48caca7c-d950-41d1-b2f3-b2dc0cfe96de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='createAccount']</value>
      <webElementGuid>e838fc43-1bc8-446b-87aa-3b7971707aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signupContainer']/button</value>
      <webElementGuid>9064b8bb-a99a-42cc-bb49-e05353438e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/following::button[1]</value>
      <webElementGuid>40a5a852-2924-4c01-9c08-d7f6d6a6f98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengalami masalah saat log in?'])[1]/following::button[2]</value>
      <webElementGuid>010f6589-2053-4f31-9724-80f1c1a78a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[2]/preceding::button[1]</value>
      <webElementGuid>61be8e59-e888-490e-a162-a96c316ef08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju untuk log in dengan menggunakan perangkat seluler'])[2]/preceding::button[1]</value>
      <webElementGuid>47c80281-525b-4b7f-a6a1-97a391d69372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>15dd09f5-094f-4d1d-8833-39f5173b718a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>21613652-90d1-48fd-8c47-1e500cb4983d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @href = '/id/webapps/mpp/account-selection' and @id = 'createAccount' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>534368e5-f4bc-4248-a066-526c861b167c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
