<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address</name>
   <tag></tag>
   <elementGuidId>95de48d7-613c-4db1-8204-cea138b9e500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingAddressId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billingAddressId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94a56307-3898-4149-824f-89a3e273825c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddressId</value>
      <webElementGuid>c45d70b5-15c0-4c21-9673-b619d75de351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_dropdown__control test_billingAddressId   </value>
      <webElementGuid>ac4a5bbe-44fb-43ee-86bd-f261a2a469a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>billingAddressId</value>
      <webElementGuid>73e9c458-e1c3-4132-9022-26d0c20a1f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddressId</value>
      <webElementGuid>8fd41c8d-9ae6-4518-bc78-270b552d23fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>b ACEH 12332+ Tambah Alamat Baru </value>
      <webElementGuid>3832fb1a-2645-4513-887a-a86e8935a6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddressId&quot;)</value>
      <webElementGuid>8b8272b2-5a00-45c0-932e-2a85fa74b178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billingAddressId']</value>
      <webElementGuid>b822a48b-0845-406e-bd5d-c74b013a566d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropdown_layout']/div/select)[2]</value>
      <webElementGuid>bb60dfcb-5196-4d72-ae26-de034f32d262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode keamanan'])[1]/following::select[1]</value>
      <webElementGuid>129f8d7a-dd26-48f7-a206-41c03eed278b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal kedaluwarsa'])[1]/following::select[1]</value>
      <webElementGuid>6ec920f9-5820-45ff-90d7-96909f55e2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat penagihan'])[1]/preceding::select[1]</value>
      <webElementGuid>036d04ba-15af-481f-b178-8c62a7166c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungkan Kartu'])[1]/preceding::select[1]</value>
      <webElementGuid>644c6a5d-69a8-418c-8a29-eab6aacd3b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>07a6382e-d747-4c37-aac5-36f4a1c70309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'billingAddressId' and @name = 'billingAddressId' and (text() = 'b ACEH 12332+ Tambah Alamat Baru ' or . = 'b ACEH 12332+ Tambah Alamat Baru ')]</value>
      <webElementGuid>aafe23ee-f154-40a8-97db-1b1815e8bdcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
