<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Card Select</name>
   <tag></tag>
   <elementGuidId>d5b86932-06a4-4bc9-8b14-2ae4842992ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='brand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81a3ecff-c204-401e-a5dd-06067ac63338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>cf39b441-4f93-4ead-a650-2aa2f9a8827f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_dropdown__control test_brand  reskin-select-white </value>
      <webElementGuid>67a05f20-fc18-4895-8710-a5a0cbfa785e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>6d9084a0-0c84-4cb9-bb57-84e0b81c1282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>b6da0059-8dae-42b1-b873-7c348184e84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih jenis kartu AndaVisaMastercardAmerican ExpressJelajahi</value>
      <webElementGuid>f34ce208-d965-4aa6-917e-c7000db62acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand&quot;)</value>
      <webElementGuid>8c4ee8b3-3958-4fc2-ac74-deb709bfea32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='brand']</value>
      <webElementGuid>e5f56917-4411-470c-927f-290051a9b510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown_layout']/div/select</value>
      <webElementGuid>e0d89216-35d6-49a5-b759-cf4cf3cd7ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor kartu debit atau kartu kredit'])[1]/following::select[1]</value>
      <webElementGuid>12345ba3-268f-4687-8e04-8f641757ca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungkan kartu'])[1]/following::select[1]</value>
      <webElementGuid>ac3685c2-dffe-4bf8-b9fa-da664634bc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis kartu'])[1]/preceding::select[1]</value>
      <webElementGuid>8e17527a-0ea1-463e-9103-3e19d923a2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal kedaluwarsa'])[1]/preceding::select[1]</value>
      <webElementGuid>8644efdc-0f47-40ed-bbfa-77f6c24d6929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3a652323-4f76-4e64-ae0d-9a154dfc2179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'brand' and @name = 'brand' and (text() = 'Pilih jenis kartu AndaVisaMastercardAmerican ExpressJelajahi' or . = 'Pilih jenis kartu AndaVisaMastercardAmerican ExpressJelajahi')]</value>
      <webElementGuid>71985646-0c82-4b13-aaed-69d4e745bdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
