<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done</name>
   <tag></tag>
   <elementGuidId>a248b1f1-8c39-46e2-b55a-7609f778ce7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.modal-ppvx2-cta.balanceDetails-moveMoneyButton.ppvx_btn.fiAction-resultButton.test_add-card-success-done.test_fiActionResult-primaryAction.ppvx_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainModal']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ef5228d-076e-449d-9c38-84c17a04885a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/flow-return/addCard?success=CC-Z8GBJDYK2RAAN</value>
      <webElementGuid>7411126c-caa9-485b-8ea6-457903a3a668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>addCardDone</value>
      <webElementGuid>84155cda-1eb4-4ec9-9f32-a17472af19e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>&quot;&quot;</value>
      <webElementGuid>a04d557a-fdb2-4903-9aca-a90c1fc7d059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-ppvx2-cta balanceDetails-moveMoneyButton ppvx_btn fiAction-resultButton test_add-card-success-done test_fiActionResult-primaryAction ppvx_btn</value>
      <webElementGuid>9d8b9787-b5a0-4cb9-8219-4b5f79abc138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>e271a76d-a45c-4b4a-b786-d7166b9815c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/div[@class=&quot;fiActionResult-container test_fi-actionResultMessage&quot;]/a[@class=&quot;modal-ppvx2-cta balanceDetails-moveMoneyButton ppvx_btn fiAction-resultButton test_add-card-success-done test_fiActionResult-primaryAction ppvx_btn&quot;]</value>
      <webElementGuid>ca45e846-b9e8-4735-a5da-f9ff0ad551fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/a</value>
      <webElementGuid>5abc32ec-dab2-448d-a749-126307015cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selesai')]</value>
      <webElementGuid>42e15e2a-b1b8-4527-b3d0-ecb94e98b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='••9660'])[1]/following::a[1]</value>
      <webElementGuid>09b27b87-24cf-4130-b2cd-9e086c65cc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>531f73b9-fe9d-4d58-b087-5772812d5c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/flow-return/addCard?success=CC-Z8GBJDYK2RAAN')]</value>
      <webElementGuid>a1077326-f9ad-40db-b172-d334e83983fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d0e0d831-2602-4536-b17f-1b8ad3b6e63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/flow-return/addCard?success=CC-Z8GBJDYK2RAAN' and (text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>80c890e2-2c5a-4622-b237-b8b8d51144fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
