<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>exp Date</name>
   <tag></tag>
   <elementGuidId>8384fe2d-4237-4afc-a891-5e13d65e5e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db1fb3dc-2984-4e9f-a090-a51b0aecbe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fb68301-2f89-4225-a2db-9f771b271e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>31055991-fd2a-43e8-ae13-8efc9a53e34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>a07f6c51-9131-4260-bbc1-07492a640d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>test_expDate vx_form-control</value>
      <webElementGuid>9b07c1b5-9529-46f8-a625-1e1bbb7a1379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/yy</value>
      <webElementGuid>e2823b1b-bf5e-47f7-b90b-4e93cc183060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46ee6599-d0f0-4906-904f-68eecf69970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expDate&quot;)</value>
      <webElementGuid>57798f1e-9674-4c6d-a030-39f76a50b809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expDate']</value>
      <webElementGuid>7432826b-b30b-44cd-9795-56d964511a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/div/div/div/form/div[4]/input</value>
      <webElementGuid>1025cc9e-ec0f-45be-a7ff-1cf4d5b50039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>fd703085-114b-439e-aeb8-abb09abec8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'expDate' and @name = 'expDate' and @placeholder = 'mm/yy']</value>
      <webElementGuid>9fd28e80-7335-43c9-a92d-1046ff050c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
