<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hubungkan Kartu</name>
   <tag></tag>
   <elementGuidId>543f5949-c37f-4c10-9710-08e414dbaea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;detailsSubmit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='detailsSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5cff9282-d369-4154-9e49-a62bf734b113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bb37d9a8-1ac7-4994-ad2e-c0f5c1064f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>0da03dbc-4c58-4241-8326-3338fe5e5f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detailsSubmit</value>
      <webElementGuid>e1c2dd7d-95e9-41ef-8687-535c6c9dc2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_wallet_add_card_form_link_pressed&quot;,&quot;includeEpoch&quot;:true,&quot;adcn_detected&quot;:&quot;no&quot;,&quot;is_billing_address_changed&quot;:&quot;no&quot;,&quot;is_billing_address_new&quot;:&quot;unknown&quot;,&quot;attempt_number&quot;:1}</value>
      <webElementGuid>560f79cc-02db-422b-a25a-da861064323e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn vx_btn add-card-submit-btn </value>
      <webElementGuid>98fe9135-37ae-4899-aa04-daa5c3f93287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87ea4f5d-94ca-4d14-99ef-cfe42af9e71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungkan Kartu</value>
      <webElementGuid>0807e106-6852-483e-b01a-b4935ae088a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/div[@class=&quot;vx_modal-body vx_blocks-for-mobile&quot;]/div[1]/div[@class=&quot;vx_modal-body vx_blocks-for-mobile&quot;]/div[@class=&quot;form-container&quot;]/form[1]/div[@class=&quot;add-fi-button-container&quot;]/button[@class=&quot;btn vx_btn add-card-submit-btn&quot;]</value>
      <webElementGuid>eaf90a87-72b8-4983-b3d4-b86f0f626a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='detailsSubmit']</value>
      <webElementGuid>9cf38dc8-6975-40ec-a9f9-82d057387e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/div/div/div/form/div[7]/button</value>
      <webElementGuid>71af6f16-56c2-487e-abe1-8c435ca56007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat penagihan'])[1]/following::button[1]</value>
      <webElementGuid>c98ea1fa-320d-4a37-92b2-d593399a4d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode keamanan'])[1]/following::button[1]</value>
      <webElementGuid>afbe922c-0df7-4f03-b132-11008eaf2d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungkan Kartu']/parent::*</value>
      <webElementGuid>a855e7b5-363a-4b6d-b5df-de97c4f8be2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>085e2796-fbdd-461c-bd0a-b04016278fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'detailsSubmit' and (text() = 'Hubungkan Kartu' or . = 'Hubungkan Kartu')]</value>
      <webElementGuid>39893d90-37af-43e3-9d4c-28b008915d99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
