<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next to Dashboard</name>
   <tag></tag>
   <elementGuidId>5b8adab6-b7f9-4478-b398-9a7e8eddbfe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalUpgradeData_submitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paypalUpgradeData_submitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85b2ab20-caf6-4b4c-8308-37703ddc54b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-ylhy9c-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>69c50504-2014-4b81-83d0-204c784eb279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.5.4</value>
      <webElementGuid>fbc736a5-ddd7-4e7a-b967-dafe08aa5bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalUpgradeData_submitBtn</value>
      <webElementGuid>a686b3d2-1b43-4e7c-9acc-a94690eea423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>go-to-home</value>
      <webElementGuid>db047d66-b330-40d1-beda-9800931e71dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>facefdc8-7d7c-4f10-b649-2feef924342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>184d9c08-9dcd-4263-b593-890f4658a040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan ke Beranda</value>
      <webElementGuid>afe2a42e-2356-48e3-a1d4-7299e072d230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalUpgradeData_submitBtn&quot;)</value>
      <webElementGuid>1871843f-a720-4341-a503-31a9826cbc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paypalUpgradeData_submitBtn']</value>
      <webElementGuid>cc126bd7-afe1-4d7a-81ad-f837336d3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div/div/div/div[3]/div/div/button</value>
      <webElementGuid>e4e817c7-0951-4be6-a620-3d4ca4c70fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perlindungan Pembeli berlaku.'])[1]/following::button[1]</value>
      <webElementGuid>0418ccf0-1989-48fa-b4c0-a10381b6b9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[1]</value>
      <webElementGuid>5a95d2ad-aefe-4b4b-90f4-e470118e8313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2024 PayPal'])[1]/preceding::button[1]</value>
      <webElementGuid>b4ad1cd2-46ed-4f57-a2a6-20a1ebe39a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privasi'])[1]/preceding::button[1]</value>
      <webElementGuid>010b5a7f-57fd-4ca1-ad93-2fa767dbbe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan ke Beranda']/parent::*</value>
      <webElementGuid>5282e9a7-21f0-4e07-b315-5cb5b18528fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>66a38054-b1e7-4f97-8758-a19f5c3b001e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'paypalUpgradeData_submitBtn' and @type = 'button' and (text() = 'Lanjutkan ke Beranda' or . = 'Lanjutkan ke Beranda')]</value>
      <webElementGuid>2e0386e0-29ce-4afe-ab61-61c441bc36d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
