<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Saldo PayPal</name>
   <tag></tag>
   <elementGuidId>f587ec0f-2d31-4f37-a724-82baa8a86ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__balance']/div/header/h3/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d06d8f70-2e61-4068-9325-b512f10b7748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      <webElementGuid>39e97af2-2f78-4d78-bf0a-555b6c109fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>fd1ce6ea-b3a8-4e50-ba5b-7628ac1abd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/</value>
      <webElementGuid>0c010ea4-8933-47a8-9057-c4ebc9712854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;domain_status&quot;:&quot;DEFAULT&quot;}</value>
      <webElementGuid>a662f114-2446-4ede-8e48-f86909249b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>balance_header</value>
      <webElementGuid>50664e27-ebd2-4719-a365-8a0ae972b58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db571aa8-0309-47dd-8a6a-6373c5e4b17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saldo PayPal</value>
      <webElementGuid>5cbc1bf0-a611-413b-93f1-5a7687eaaa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__balance&quot;)/div[@class=&quot;cw-card cw-card--full-click cw_balance css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__content&quot;]/a[@class=&quot;css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong&quot;]</value>
      <webElementGuid>51185be3-68db-4612-8c7d-af4fac4678e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__balance']/div/header/h3/div/div/a</value>
      <webElementGuid>c862e932-7e83-4305-85f1-5fdf02e57ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Saldo PayPal')]</value>
      <webElementGuid>ae3a4501-3299-4cd6-a5b3-b0627fa0eee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::a[1]</value>
      <webElementGuid>59c82058-515c-4ba1-9437-8df78c389f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal: Ringkasan'])[2]/following::a[1]</value>
      <webElementGuid>6b706a00-ff88-4a1e-8261-674752b22cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='overflowMenu_balance'])[1]/preceding::a[1]</value>
      <webElementGuid>94de959a-23f9-41f7-ba30-2a7a01e114f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buka saldo PayPal'])[1]/preceding::a[1]</value>
      <webElementGuid>7046d0b4-e984-41e2-bbb9-0dae2083d0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saldo PayPal']/parent::*</value>
      <webElementGuid>622522e1-d68d-4ae6-957e-5560b36409fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/')]</value>
      <webElementGuid>486a11c0-9e0f-454b-8e98-53a8c24146a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/div/a</value>
      <webElementGuid>49bdd7bb-1e5e-4ebc-800f-4fb57c91f065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/' and (text() = 'Saldo PayPal' or . = 'Saldo PayPal')]</value>
      <webElementGuid>0067b5f5-c4fe-4c31-895a-e5f4fa7c1b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
