<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selesai</name>
   <tag></tag>
   <elementGuidId>c414ea88-1957-44d5-9983-7b6e66123124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.modal-ppvx2-cta.balanceDetails-moveMoneyButton.ppvx_btn.fiAction-resultButton.test_add-card-success-done.test_fiActionResult-primaryAction.ppvx_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainModal']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab14bd44-2b07-4dda-a549-2c8983a7f1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/flow-return/addCard?success=CC-QS3VNPDDCRAR4</value>
      <webElementGuid>7beaeab5-e508-4c60-9140-9bac580b1852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>addCardDone</value>
      <webElementGuid>068398de-1dca-4eb2-972a-8a6b46cfe596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>&quot;&quot;</value>
      <webElementGuid>ab59b7a6-a816-4273-9f8f-c8ea87828b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-ppvx2-cta balanceDetails-moveMoneyButton ppvx_btn fiAction-resultButton test_add-card-success-done test_fiActionResult-primaryAction ppvx_btn</value>
      <webElementGuid>58cb180b-5f78-4720-8e46-8fc5abf675af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>508dd2ed-b7dd-43cc-8df0-18ba013d8136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/div[@class=&quot;fiActionResult-container test_fi-actionResultMessage&quot;]/a[@class=&quot;modal-ppvx2-cta balanceDetails-moveMoneyButton ppvx_btn fiAction-resultButton test_add-card-success-done test_fiActionResult-primaryAction ppvx_btn&quot;]</value>
      <webElementGuid>681032e1-c72e-422d-933c-4f93629424e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/a</value>
      <webElementGuid>7e1eae8c-90ab-4da7-b5dd-089b259715de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selesai')]</value>
      <webElementGuid>6a83b929-d3b4-4d91-8822-1b368c2ce5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='••9660'])[1]/following::a[1]</value>
      <webElementGuid>d6ce29af-2ac8-4c0f-abc1-b335b4d91ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>1fe006bd-f0f2-417d-8939-5105c7a12a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/flow-return/addCard?success=CC-QS3VNPDDCRAR4')]</value>
      <webElementGuid>8eb1802c-9623-4256-9694-ea43ed53bd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>b77022df-6a5b-4036-adeb-11f935b95620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/flow-return/addCard?success=CC-QS3VNPDDCRAR4' and (text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>91ba7ca4-dcfd-4b40-8650-8be691794f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
