<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verification Code</name>
   <tag></tag>
   <elementGuidId>f2b2d3f8-3193-4033-9bf3-320b88e46242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verificationCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verificationCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc2034d9-8b1b-4b45-9d97-4eb716867667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4ea68b72-6651-4d81-be3e-0c99b229204d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verificationCode</value>
      <webElementGuid>c089fa1f-d5b4-4152-863e-c782b1916a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verificationCode</value>
      <webElementGuid>ee9c557f-109f-43ec-a710-91503e779a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>test_verificationCode test_verificationCode</value>
      <webElementGuid>4bdae928-7d5d-4cbc-b643-d24acd2297a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode keamanan</value>
      <webElementGuid>40c67673-2f59-4ff3-bc20-902eef5823d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>89f8d970-00b3-4142-87dd-c3a73994f9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>text-info-verificationCode</value>
      <webElementGuid>4e2d70bb-5399-4829-b4bc-ef73ce1ec7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verificationCode&quot;)</value>
      <webElementGuid>e855f180-0a39-4ec8-a12f-205edf8afbe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verificationCode']</value>
      <webElementGuid>ae611a7f-c549-47e8-9e7f-52e02fd12ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/div/div/div/form/div[5]/div/div/div/div/input</value>
      <webElementGuid>2d94c153-c2f2-413b-a521-e33b6ff5533d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>f02d7922-cbcf-4581-85ad-d6a9e440e0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'verificationCode' and @name = 'verificationCode' and @placeholder = 'Masukkan kode keamanan']</value>
      <webElementGuid>0b865fa3-e2e5-480a-809f-501a867cd43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
