<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transaction 1 detail</name>
   <tag></tag>
   <elementGuidId>fa17082f-0d7c-42d6-ad8b-c8f8944fa674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trans_overview_root_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trans_overview_root_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>548eb159-693a-44cf-9b1c-7b5099891a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trans_overview_root_container</value>
      <webElementGuid>826aa4e8-acdf-4352-a68e-93969c21791f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>trans_overview_root_container</value>
      <webElementGuid>91bcab28-df04-4947-b3c7-78653db3fbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-block-type</name>
      <type>Main</type>
      <value>FLEX_CONTAINER</value>
      <webElementGuid>8ff8718c-a8e0-4888-aab9-08f939ffda42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity_transaction_overview css-zwrdg2-Block</value>
      <webElementGuid>cceea4f1-3896-4719-bf08-db507eb07d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ttestingardellia@example.com+120,00 $20 Sep . Refund</value>
      <webElementGuid>9891b4ea-525b-4fdf-ae87-28dd0c0bbd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;ZRTc1&quot;]/div[@class=&quot;CYYwi&quot;]/div[@class=&quot;ppvx_row___2-7-9&quot;]/div[@class=&quot;ppvx_col-sm-12___2-7-9 jLgiM&quot;]/div[2]/div[@class=&quot;list_item js_transactionItem-91K18292MX122131Y&quot;]/div[@class=&quot;ppvx_tile___2-9-12 ppvx_tile--card___2-9-12 ppvx--v2___2-9-12 ppvx_tile--card--size_xs-long___2-9-12 Cf3Gg transaction-list-tile-container&quot;]/div[@id=&quot;activity_transaction_overview&quot;]/div[@id=&quot;trans_overview_root_container&quot;]</value>
      <webElementGuid>491078bc-6e47-4694-ba22-0602c965af48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='trans_overview_root_container']</value>
      <webElementGuid>32065998-6e0c-4b32-82e6-7f3a522d7b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activity_transaction_overview']/div</value>
      <webElementGuid>291f98c8-9b62-4d41-aa93-518a53c48366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This week'])[1]/following::div[3]</value>
      <webElementGuid>4cd2f358-aeee-4dbe-961c-1db7406c6041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::div[12]</value>
      <webElementGuid>66afb4ad-8130-48fe-9e3d-84c454e67336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>7cf11505-05d5-43d6-af0b-630a90311b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'trans_overview_root_container' and (text() = 'Ttestingardellia@example.com+120,00 $20 Sep . Refund' or . = 'Ttestingardellia@example.com+120,00 $20 Sep . Refund')]</value>
      <webElementGuid>6e0187c3-1795-4241-b989-9a715a0a2d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
