<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account Number</name>
   <tag></tag>
   <elementGuidId>96606d34-5c77-4b62-8ce5-3a753422f7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vx_form-group.vx_floatingLabel.vx_floatingLabel_active.hasValue.vx_has-message.vx_floatingLabel_complex > div.vx_form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainModal']/div/div/div/form/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5197c79-705c-4c49-b44a-0703daa4a0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vx_form-control</value>
      <webElementGuid>65865494-fd1e-4e4a-a86d-ac62708ea098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-content</name>
      <type>Main</type>
      <value>Account Number</value>
      <webElementGuid>eb41cc58-a11e-49a8-a0d5-e1c9b387bd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/form[1]/div[@class=&quot;vx_form-group vx_floatingLabel vx_floatingLabel_active hasValue vx_has-message vx_floatingLabel_complex&quot;]/div[@class=&quot;vx_form-control&quot;]</value>
      <webElementGuid>741df3db-0d9b-4814-bed5-dc1711bcc4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/div[4]/div</value>
      <webElementGuid>38cbcad3-7d5a-4fec-9d16-36146b5a3069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number'])[1]/following::div[1]</value>
      <webElementGuid>66c0d50f-50e0-4461-8bf2-efac6f5e1ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank code'])[1]/following::div[3]</value>
      <webElementGuid>ebaa37e3-2cee-488b-a969-b62a05ce59a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::div[2]</value>
      <webElementGuid>954b7098-d7ae-4eef-bd8e-c8c9d92cec81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Your Bank'])[1]/preceding::div[3]</value>
      <webElementGuid>dca73cb2-3d43-4d7b-b0d0-3338be98b2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div</value>
      <webElementGuid>62983b98-ed87-44fc-9077-0a7862c58089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
