<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank code</name>
   <tag></tag>
   <elementGuidId>35a2abb1-7925-4cbf-8b2d-5d18251ce0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#routingNumberGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='routingNumberGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b091772-eca0-40d1-b006-04be17418d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ccd54ee-cb21-4ad7-8701-a22ba0ba69c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>routingNumberGroup</value>
      <webElementGuid>5bc19f22-033d-4dcb-a33a-8711b3d87ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routingNumberGroup</value>
      <webElementGuid>bfba9c67-7cd2-4e50-a707-19f41ebc39eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>test_routingNumberGroup</value>
      <webElementGuid>00fffb65-d87a-40ac-8178-075a9f1df960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80a3236b-b42d-4420-9ddd-5dc3b4ddd2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>text-info-routingNumberGroup</value>
      <webElementGuid>cb596ca1-7f3d-4b66-8536-615bae9ad7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routingNumberGroup&quot;)</value>
      <webElementGuid>d9199caa-7bc9-4379-bfc9-3a05e794d309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='routingNumberGroup']</value>
      <webElementGuid>f08d4d45-7cf2-43d4-9988-ff66563b7d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>b3de04f9-c44a-47f4-b589-84949eba98d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>71ca0b37-c4be-4fef-9d34-5948948d4124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'routingNumberGroup' and @name = 'routingNumberGroup']</value>
      <webElementGuid>c6666e70-2deb-4edf-a4bd-85e935629265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
