<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank Name (1)</name>
   <tag></tag>
   <elementGuidId>20c21120-cb9e-4deb-9ca5-8a0737829212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autoComplete-searchBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autoComplete-searchBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ebec389-e704-4d7b-8ce7-6a48564e6da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c669910-eb6c-4808-a44e-313833bbd135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete-searchBox</value>
      <webElementGuid>2dfe0572-6d48-4a85-8146-ca8c48a91b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autoComplete-searchBox</value>
      <webElementGuid>e1fb55db-5858-46ab-aaf1-358c5e38f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>test_autoComplete-searchBox autocomplete-searchInput no-outline  vx_form-control</value>
      <webElementGuid>d5128b00-0ca7-44c8-92e2-a168c347413a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e74d58e-5579-4cec-bdae-abc8e665c5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>3f68efb1-cbcf-4bd0-aba6-fe2301fedb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>autoComplete-searchBoxLabel</value>
      <webElementGuid>ff2bc40b-bd84-49db-90d7-c3f222bd95fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7989bb9b-7ab7-4658-a6bf-257a7753a87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a2f8371-559b-4c21-b5d7-51cd4e1ede7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>55a8e21a-8189-432e-bdc1-19f99a1e1065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete-searchBox&quot;)</value>
      <webElementGuid>25169b76-f415-46bf-9708-d08ac479f20a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autoComplete-searchBox']</value>
      <webElementGuid>cd5f5e6b-e5ac-4486-ac1c-5bb5ee945c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/div/div/input</value>
      <webElementGuid>3a7daaea-39c4-46cd-9b61-e51835ad8e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>925c8660-ed67-4b04-8830-3abec12402ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'autoComplete-searchBox' and @name = 'autoComplete-searchBox']</value>
      <webElementGuid>534272fc-7a5d-4e8e-93ff-5874104c26cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
