<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>db9145d5-681b-409b-af2d-0dce50bbd991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;next&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0021d99-242f-4694-96fc-60c1e0914e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9fee925b-30f4-4130-9f99-3c0ebad8accc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>149fda71-a85b-405b-811f-f3ccee5e9c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>2d1ab731-e1e2-4c73-be6f-632718aabe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;amt&quot;:1000,&quot;is_prefill_changed&quot;:&quot;y&quot;,&quot;is_decimal&quot;:&quot;n&quot;,&quot;erpgTransfers&quot;:&quot;&quot;,&quot;eccd&quot;:&quot;&quot;}</value>
      <webElementGuid>a7e7b2b0-6419-408e-8784-cd002e43770b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn vx_btn vx_btn-block test_analyze-withdraw-submit </value>
      <webElementGuid>9f63e014-851f-476a-aa4a-9cb67c33a5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>db220b68-099e-472d-bb11-53f47ba7b465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/form[1]/button[@class=&quot;btn vx_btn vx_btn-block test_analyze-withdraw-submit&quot;]</value>
      <webElementGuid>1f4dfc02-66d3-449c-9faf-37d6ce724070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='next']</value>
      <webElementGuid>658bf112-f0d0-41e5-8d3e-7bf63f59c495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/button</value>
      <webElementGuid>7a91c2f5-cdf3-4221-9ef3-fe55998fe11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available PayPal balance'])[1]/following::button[1]</value>
      <webElementGuid>19a6ef39-9eb3-4ee8-995c-82fbff457c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::button[1]</value>
      <webElementGuid>f6d0e8a4-3d2f-42da-9675-629b38850b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::button[1]</value>
      <webElementGuid>5ebb1655-ecdb-49c5-9f8c-19b46b7fac73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::button[1]</value>
      <webElementGuid>befec07c-0861-4280-a97a-baab85e3b920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>8ce9e6d2-346f-4cbb-bb4e-8d715f35d04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c043def8-ec86-4a7e-8e67-21daace337cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>61e0fb12-4c6e-42e3-9fd5-3115f3f1d7b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
