<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cross</name>
   <tag></tag>
   <elementGuidId>e1e1ac48-8e37-4a2a-9007-c32879d347cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;clear&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainModal']/div/div/div/form/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13046f73-21ec-4399-8d2f-c725c72172f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.paypalobjects.com/mnw-assets/add_icon_grey.svg</value>
      <webElementGuid>e672766a-f050-44ad-bb35-8d27dda0f0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>clear</value>
      <webElementGuid>088a9a1f-6843-42ca-a307-cf3782ebdbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainModal&quot;)/div[@class=&quot;vx_modal-wrapper-backgroundOverride vx_modal-wrapper elementDirection vx_modal-wrapper_logo&quot;]/div[1]/div[@class=&quot;vx_modal-content&quot;]/form[1]/div[1]/div[@class=&quot;table-row amountComponent-container&quot;]/div[@class=&quot;amountInput-container elementDirection_ltr amountInput-container-redesign&quot;]/a[@class=&quot;clear-text-link currencyPart&quot;]/img[1]</value>
      <webElementGuid>78fba913-d724-40ed-aaca-c99f6ccfbcdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/div/div/div/a/img</value>
      <webElementGuid>bd6696a3-b872-4515-9c0a-8aff28cc7b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='clear']</value>
      <webElementGuid>3b557570-afbe-45b4-8ad0-dc9d10d78b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e23b991b-4eae-4992-a0a9-b00f73e73a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.paypalobjects.com/mnw-assets/add_icon_grey.svg' and @alt = 'clear']</value>
      <webElementGuid>6976550f-c4c1-4f47-a1e8-3d2767b157fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
