<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Your PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK. Checking 2548 is linked</name>
   <tag></tag>
   <elementGuidId>7d45ee2e-cb8c-45ec-a991-b249f6575cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_modalHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='js_modalHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>041bf7da-5b83-4904-88a0-984cbc072555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_modalHeader</value>
      <webElementGuid>3c5b8633-b384-4f30-bad8-2967d81dca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>6d617d76-ef86-4b91-abe8-f0e12dd1a0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text--heading-sm fiActionResult-header test_fiActionResult-header </value>
      <webElementGuid>af407cff-8dbf-4d56-b750-795b46edc29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK. Checking ••2548 is linked</value>
      <webElementGuid>81edf772-2dd0-4950-97de-944160651f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_modalHeader&quot;)</value>
      <webElementGuid>716ae8cb-220d-4b35-80d4-587604aaebde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='js_modalHeader']</value>
      <webElementGuid>66b230b5-0b2e-4c6f-82b6-72ec8f13c546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/h2</value>
      <webElementGuid>25d43742-8ed0-466e-9378-58835328ee65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::h2[1]</value>
      <webElementGuid>bb00be98-170d-4c9e-bb81-6dde7cc41131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::h2[1]</value>
      <webElementGuid>24bab106-39e6-4a4c-ba0f-5253396322ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK. Checking']/parent::*</value>
      <webElementGuid>607f6c30-8fc6-4ae4-b94b-4c2dd7c24c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f547f149-c0ec-40fd-8cd6-e70b2c232b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'js_modalHeader' and (text() = 'Your PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK. Checking ••2548 is linked' or . = 'Your PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK. Checking ••2548 is linked')]</value>
      <webElementGuid>897d2bee-a72e-4882-b3e1-e30eec7d50f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
