<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>insert amount</name>
   <tag></tag>
   <elementGuidId>2c25f376-ff89-4e8f-8ad6-a7d6dfe11268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_withdrawInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='js_withdrawInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6b7c307-e9c3-4b46-b7c9-a9a1aa137225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0da368d6-c0f5-4f60-8fae-7b4e361ebdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_withdrawInput</value>
      <webElementGuid>833535c1-c1f8-40a9-adf9-0e2a413354a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>js_withdrawInput</value>
      <webElementGuid>b0aaf8c3-a8b5-4395-8ace-bd48c1c5b9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amountInput  test_amountInput</value>
      <webElementGuid>39dd1c28-d341-4c43-9bca-4585b8a16bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f171f526-cf2c-4816-b2f1-222e815aabe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4.337,90</value>
      <webElementGuid>20825589-65cc-405c-8055-6a248959cee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_withdrawInput&quot;)</value>
      <webElementGuid>b9487de4-b0bc-45f4-9701-35f9d90c1c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='js_withdrawInput']</value>
      <webElementGuid>546ed209-2b4b-48fa-9876-9c26283129c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>8aad779c-7b92-454d-9115-2b1fc15819ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9ecf9bf8-7129-4e96-b631-6b7ac36bfbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'js_withdrawInput' and @name = 'js_withdrawInput']</value>
      <webElementGuid>c4e8d4ff-ae1b-4aaf-82eb-a3f87734ba84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
