<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link a bank (1)</name>
   <tag></tag>
   <elementGuidId>81bf839e-98f4-48ca-8dd7-4ca90f244e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ppvx_link.interstitial-entryLink.test_addNewBank</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='contents']/main/div/div/section/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78914f86-f965-46c5-93db-0efacd88785d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/banks/new</value>
      <webElementGuid>f0729172-389a-437b-895d-ac0a55372454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>addBank</value>
      <webElementGuid>4e7f4e95-85ac-4589-b8cc-a38004d381b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_link interstitial-entryLink test_addNewBank</value>
      <webElementGuid>29bb50c6-6aab-40c2-b883-0e0c853f71a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b0a5db6-21b8-41c7-86fa-d6c6600df069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link a bank</value>
      <webElementGuid>cb555851-bbcd-4a53-aca8-77dbcd3cea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contents&quot;)/main[@class=&quot;row accountPage-container js_accountPage-container elementDirection&quot;]/div[@class=&quot;col-sm-4 accountPage-sections fiLists-container isActive&quot;]/div[@class=&quot;fiLists-container-spacing&quot;]/section[@class=&quot;fiList-icon_container&quot;]/div[@class=&quot;fiList-icon_sideBySide&quot;]/a[@class=&quot;ppvx_link interstitial-entryLink test_addNewBank&quot;]</value>
      <webElementGuid>da81e4ff-8bdd-4784-a876-d8e8663789f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contents']/main/div/div/section/div/a</value>
      <webElementGuid>7dace6a5-9c29-4311-9a06-ec1f92c8dbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[3]/following::a[1]</value>
      <webElementGuid>486eb0ed-d767-41b6-9c21-897c1603647e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[3]</value>
      <webElementGuid>c80c3be1-ef31-4bbc-8985-0c41854013d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link a card'])[2]/preceding::a[1]</value>
      <webElementGuid>c4147305-bd20-4870-9224-d2a4ce8013d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/banks/new')]</value>
      <webElementGuid>c472813e-c69b-4420-8efa-cd7a420eb1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/a</value>
      <webElementGuid>f51c48cc-0052-4c68-8d80-baa659ffbfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/banks/new' and (text() = 'Link a bank' or . = 'Link a bank')]</value>
      <webElementGuid>ee592152-a00d-46e8-860a-abda3ac66fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
