<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link a bank</name>
   <tag></tag>
   <elementGuidId>12a36082-93af-4eed-bcd8-62fa0eb31d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ppvx_link.interstitial-entryLink.test_addNewBank</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='contents']/main/div/div/section/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab7020cb-9312-4970-8f52-b504990f901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/banks/new</value>
      <webElementGuid>5435e967-92f2-413c-8b3e-0bb94a5aee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>addBank</value>
      <webElementGuid>cb274369-2044-4a22-a4f2-45ba6adae601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_link interstitial-entryLink test_addNewBank</value>
      <webElementGuid>0e0d0dec-54a5-4691-8a84-cb3d2a907533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cfa3aed9-b9ac-4f91-9286-586b9cd5e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link a bank</value>
      <webElementGuid>1c044494-9058-4f97-9b30-e73cfda9f354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contents&quot;)/main[@class=&quot;row accountPage-container js_accountPage-container elementDirection&quot;]/div[@class=&quot;col-sm-4 accountPage-sections fiLists-container isActive&quot;]/div[@class=&quot;fiLists-container-spacing&quot;]/section[@class=&quot;fiList-icon_container&quot;]/div[@class=&quot;fiList-icon_sideBySide&quot;]/a[@class=&quot;ppvx_link interstitial-entryLink test_addNewBank&quot;]</value>
      <webElementGuid>d8a2836b-4f89-4a84-9f76-c634a009a449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contents']/main/div/div/section/div/a</value>
      <webElementGuid>17ec6bb5-5c4b-43d4-a426-8c99451750c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[3]/following::a[1]</value>
      <webElementGuid>43a1ca64-f5da-480e-a7f2-7df7daa09f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[3]</value>
      <webElementGuid>a33b6ad8-9bf4-4f6b-8261-6c0e3f535b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link a card'])[1]/preceding::a[1]</value>
      <webElementGuid>db6131bb-bd62-4861-9fea-673b2e12fc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/banks/new')]</value>
      <webElementGuid>7339b61d-d73c-4d4b-828d-80c70c876779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/a</value>
      <webElementGuid>b7d42faa-e6a0-4919-9e23-f9f694caeda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/banks/new' and (text() = 'Link a bank' or . = 'Link a bank')]</value>
      <webElementGuid>0aacdb93-fb4f-457e-b0ac-f78e6697f841</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
