<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link a card</name>
   <tag></tag>
   <elementGuidId>f5b61b77-a74f-45bd-87aa-b94014fe03c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ppvx_link.interstitial-entryLink.test_addNewCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='contents']/main/div/div/section/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>590e51ce-7859-43ec-a626-d60702750176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/cards/new</value>
      <webElementGuid>cb67f303-c92c-4c08-ba9a-88405eb4934a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>addCard</value>
      <webElementGuid>2b714cb3-9f0f-4551-97df-b79d365cde6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;isNewContext&quot;:true,&quot;event_name&quot;:&quot;dw_wallet_cards_add_card_pressed&quot;,&quot;platform&quot;:&quot;web&quot;,&quot;source&quot;:&quot;wallet_add_card_button&quot;,&quot;flow&quot;:&quot;wallet&quot;}</value>
      <webElementGuid>4b3ee3db-45c1-4ff7-9795-e99f6f8ea0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_link interstitial-entryLink test_addNewCard</value>
      <webElementGuid>b0e1253b-0332-475c-bc73-feda80bb3045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4ad844e2-6a8b-4231-8ace-411712e5e3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link a card</value>
      <webElementGuid>a483bd01-8877-48d4-8549-dbb81e81f783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contents&quot;)/main[@class=&quot;row accountPage-container js_accountPage-container elementDirection&quot;]/div[@class=&quot;col-sm-4 accountPage-sections fiLists-container isActive&quot;]/div[@class=&quot;fiLists-container-spacing&quot;]/section[@class=&quot;fiList-icon_container&quot;]/div[@class=&quot;fiList-icon_sideBySide&quot;]/a[@class=&quot;ppvx_link interstitial-entryLink test_addNewCard&quot;]</value>
      <webElementGuid>7bafaf07-4ab4-4a12-b236-a2163d8ceb17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contents']/main/div/div/section/div[3]/a</value>
      <webElementGuid>930c09ea-8eff-45cf-a578-f1a8c507b82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link a bank'])[1]/following::a[1]</value>
      <webElementGuid>a4849658-4e0b-4a25-9930-63cbeb5a1dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[3]/following::a[2]</value>
      <webElementGuid>c12e8e6c-2023-409e-9db3-1778b9548e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal balance'])[1]/preceding::a[1]</value>
      <webElementGuid>1011cd58-46f2-4c0b-a7ba-97bb7efafd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/cards/new')]</value>
      <webElementGuid>6825ff0c-ca20-4f8d-8f04-37e0d73a49ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>dc0dc917-d9ae-4c83-aaee-fd4df315192f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/cards/new' and (text() = 'Link a card' or . = 'Link a card')]</value>
      <webElementGuid>1da9e1a9-2601-46f9-900b-3385b03592c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
