<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK</name>
   <tag></tag>
   <elementGuidId>a8be242f-1248-46dc-9971-38beed4d19ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-1-item-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-1-item-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d89526f7-9477-413e-984f-5548c3873800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-1-item-0</value>
      <webElementGuid>7ae35cbb-53cd-42ff-81cd-6a01f0f9a857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0507f248-6e5d-4049-ac97-9ae285e33dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e059cb69-59ad-4089-a0a9-66e8b56a4ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete-listItem test_searchItem-bank autocomplete-listItem_highlighted </value>
      <webElementGuid>384a70e8-78b5-420f-b634-fba1fceb0152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>selectBank</value>
      <webElementGuid>c82956cd-f78b-4253-8756-cc3e053de2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;issuer_name&quot;:&quot;PT._BANK_NEGARA_INDONESIA_1946_(PERSERO)_TBK.&quot;,&quot;ct_cnt&quot;:21,&quot;sugg_cnt&quot;:1,&quot;vendor_name&quot;:&quot;&quot;,&quot;ob_link_method&quot;:&quot;&quot;}</value>
      <webElementGuid>4a99288e-05ca-41fd-be0c-1a8abc7583f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.</value>
      <webElementGuid>d9d07050-2750-4cd6-8159-c3840169f258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-1-item-0&quot;)</value>
      <webElementGuid>b4e31cb1-c221-45c5-81b4-4bd46c770778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='downshift-1-item-0']</value>
      <webElementGuid>94528aeb-c4d7-4e09-a96f-a96ed4914714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='downshift-1-menu']/li</value>
      <webElementGuid>b125e158-39ec-4c42-87ec-a4fe3f288deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Name'])[1]/following::li[1]</value>
      <webElementGuid>a80b3933-9a17-4f6e-b012-b8e76ab1e3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can only link a bank account in Indonesian rupiah.'])[1]/following::li[1]</value>
      <webElementGuid>d0135be3-8de1-4c48-883a-91456bbc54a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>83b14817-6aa6-41d7-be0b-cb86f4f643e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'downshift-1-item-0' and (text() = 'PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.' or . = 'PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.')]</value>
      <webElementGuid>76fa8e4e-74e8-48c2-972d-856e796b960b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
