<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Transferred</name>
   <tag></tag>
   <elementGuidId>c337644c-e648-45b4-abc4-e3ec41f2cbe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_modalHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='js_modalHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fa2873be-ce84-437a-a916-4a653cf9468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_modalHeader</value>
      <webElementGuid>c49cc3de-d9bc-473a-bbfb-a7cd7be99e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>4e3b0c3d-c5c7-4eb9-b5a9-6228d6c4894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text--heading-sm fiActionResult-header test_fiActionResult-header </value>
      <webElementGuid>e3175db7-3a57-432b-9209-a46beaf2b73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You transferred 133.273 Rp IDR</value>
      <webElementGuid>896249b3-31bd-4627-af45-f1fff13f2027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_modalHeader&quot;)</value>
      <webElementGuid>18a8648e-4195-436a-b8ec-e49730fbce89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='js_modalHeader']</value>
      <webElementGuid>2a352f51-6c61-44b6-8a1f-add8e12e2930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainModal']/div/div/div/div/h2</value>
      <webElementGuid>e540b2eb-fb3e-4f49-8f43-153f531146de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::h2[1]</value>
      <webElementGuid>d94f1559-7291-4847-ab00-15155d459772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='••2548'])[1]/preceding::h2[1]</value>
      <webElementGuid>e9d5467e-69eb-4900-9412-370110900096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You transferred 133.273 Rp IDR']/parent::*</value>
      <webElementGuid>44b670a4-b2af-47c2-ab9e-111ad0c46c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>20b93af7-1276-4f44-9c65-a15cb993587c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'js_modalHeader' and (text() = 'You transferred 133.273 Rp IDR' or . = 'You transferred 133.273 Rp IDR')]</value>
      <webElementGuid>9bfdde40-79be-4657-81da-9f3eb168ca71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
