<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create an invoice</name>
   <tag></tag>
   <elementGuidId>ba056ff7-3ed5-4601-a617-239d294fe9f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-io89zt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c859331-5bde-44ef-b182-373875693937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-io89zt</value>
      <webElementGuid>99a9398a-b7d2-4e67-97d0-00acdc14e46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an invoiceCreate an invoiceCustomize, track, and send invoices.Covered by Seller Protection  where eligible.Get Started</value>
      <webElementGuid>5a4cdae3-4685-43ec-8bef-8fce10b08ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[1]/div[@class=&quot;css-18v44rk&quot;]/div[@class=&quot;css-1oxxbhp&quot;]/div[@class=&quot;css-ybnhtb&quot;]/div[@class=&quot;css-1ymbc7y&quot;]/div[@class=&quot;css-io89zt&quot;]</value>
      <webElementGuid>7de1fff3-4f66-457c-8d0e-312a2a400750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>4c2ac68a-255a-462f-8c37-e96fe2d331b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll right'])[1]/following::div[6]</value>
      <webElementGuid>a444ec5d-8129-4ebb-80f6-9d679a9a5d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scroll left'])[1]/following::div[6]</value>
      <webElementGuid>481ab555-ba5b-4c93-beda-78bc78f583c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>cc0dac05-4b91-41cc-b8b8-d608c2a8a789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create an invoiceCreate an invoiceCustomize, track, and send invoices.Covered by Seller Protection  where eligible.Get Started' or . = 'Create an invoiceCreate an invoiceCustomize, track, and send invoices.Covered by Seller Protection  where eligible.Get Started')]</value>
      <webElementGuid>ec2bc823-b0f0-4862-a143-7d0b64ac680f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
