<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Activity no 1</name>
   <tag></tag>
   <elementGuidId>31186c91-2c65-4f33-8b17-5dd0dfe237ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trans_overview_root_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trans_overview_root_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>302acef8-a87d-4159-a5fe-6c6400542f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trans_overview_root_container</value>
      <webElementGuid>1c4d8089-a529-4509-89ca-3ab6a80d36c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>trans_overview_root_container</value>
      <webElementGuid>832a50cf-97ce-43df-a798-a9605a845ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-block-type</name>
      <type>Main</type>
      <value>FLEX_CONTAINER</value>
      <webElementGuid>51d9af68-cb93-4344-9889-b511f12501d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity_transaction_overview css-zwrdg2-Block</value>
      <webElementGuid>245ec2e0-e067-4b40-8b9a-921a8edc3e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ttestingardellia@example.com+120,00 $20 Sep . Refund</value>
      <webElementGuid>c4d98c89-28f3-49b3-a101-b59dfe28d042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-enhancement-container&quot;)/div[@class=&quot;ppvx_tile___2-9-12 ppvx_tile--card___2-9-12 ppvx--v2___2-9-12 ppvx_tile--card--size_xs-long___2-9-12 widgetItemContainer&quot;]/div[@id=&quot;activity_transaction_overview&quot;]/div[@id=&quot;trans_overview_root_container&quot;]</value>
      <webElementGuid>329748ad-88d6-4879-ac4e-d1d94c939446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='trans_overview_root_container']</value>
      <webElementGuid>be93fd77-ed0e-40f6-942b-b9837a95c50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activity_transaction_overview']/div</value>
      <webElementGuid>5f8fe02e-e7bc-4a4b-bc22-f28f788e7615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent activity'])[1]/following::div[4]</value>
      <webElementGuid>484ed5d4-49d8-457d-8ebb-85df854a9019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/following::div[18]</value>
      <webElementGuid>56f4e6e0-eaf3-49e2-9eda-7ec4f97b663d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>609ee175-e326-42bf-bd58-1849965fcab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'trans_overview_root_container' and (text() = 'Ttestingardellia@example.com+120,00 $20 Sep . Refund' or . = 'Ttestingardellia@example.com+120,00 $20 Sep . Refund')]</value>
      <webElementGuid>b9b36ec3-47e2-4f41-ae29-64ce363dbee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
