<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Aktivitas</name>
   <tag></tag>
   <elementGuidId>2d0eb4bb-6a53-4aae-b067-c8392ec8f7d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_navbar__primary-item.js_activity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Aktivitas')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed82d831-ed70-41e0-8def-0e9cc7583d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/activity</value>
      <webElementGuid>c29bfe39-3f9e-4518-9165-afad249ef2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>8430522e-a8e8-403e-9a71-d4e5fb5493dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_pressed&quot;}</value>
      <webElementGuid>c2de6487-3970-4e2b-9757-0134d3e3f215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;item_name&quot;:&quot;dw_nav&quot;,&quot;link_name&quot;:&quot;activity&quot;,&quot;default_tab&quot;:&quot;wallet&quot;,&quot;product&quot;:&quot;dw_nav&quot;,&quot;module&quot;:&quot;header&quot;,&quot;card_type&quot;:&quot;nav_header_activity&quot;,&quot;tile_id&quot;:&quot;nav_header_activity&quot;,&quot;scope&quot;:&quot;tile&quot;}</value>
      <webElementGuid>663d1019-d2d8-427c-9901-086b8ba397ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__primary-item js_activity</value>
      <webElementGuid>464ca434-4182-4061-9ba4-77ae66d5008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-av-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_loaded&quot;}</value>
      <webElementGuid>c1ff2fd3-d6dd-4b8a-a5b5-ebd4fd26eba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_shown&quot;}</value>
      <webElementGuid>04931c2f-8fb7-4ae7-adac-74fa46e3e136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b783fd10-6ea8-4041-957d-e3b3d0c6f387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktivitas</value>
      <webElementGuid>e544b9f6-eb81-4498-8b8a-612c05c77d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cw_root cw_navbar_enabled&quot;]/div[2]/div[@class=&quot;cw_navbar_drawer cw_drawer_closed&quot;]/div[@class=&quot;cw_navbar cw_navbar--wide&quot;]/div[@class=&quot;cw_navbar__mainnav&quot;]/nav[@class=&quot;cw_navbar__nav&quot;]/ul[@class=&quot;cw_navbar__primary&quot;]/li[4]/a[@class=&quot;cw_navbar__primary-item js_activity&quot;]</value>
      <webElementGuid>f8f81969-e04c-4c31-8b44-62bce5c69917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aktivitas')]</value>
      <webElementGuid>870f51ed-7c73-4227-9f02-cde7414a1139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/following::a[1]</value>
      <webElementGuid>8379bd22-9c99-4339-ae50-9ef31ec0d9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim dan Minta'])[1]/following::a[2]</value>
      <webElementGuid>78852ca4-8a3d-4c7a-884e-228cc3f91231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/preceding::a[1]</value>
      <webElementGuid>4b687970-2720-4d1e-a335-74ddd07fff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemberitahuan'])[1]/preceding::a[2]</value>
      <webElementGuid>2c30785a-3463-4a1e-ac69-75e0a0ddb5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktivitas']/parent::*</value>
      <webElementGuid>f343c37e-634c-45e8-a270-d97f9bd7ec20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/activity')]</value>
      <webElementGuid>3ceafc27-4a5c-4128-befb-fd6cbd56b62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>06cf44a3-6406-451d-9595-2ec562c004da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/activity' and (text() = 'Aktivitas' or . = 'Aktivitas')]</value>
      <webElementGuid>7a575087-1cd1-4ed9-8d35-6cfb40779498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
