<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BANK 1</name>
   <tag></tag>
   <elementGuidId>40b0f171-2da0-4509-9e52-2b2f1c3cf499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fi_list_item.cw-header__link.bankFI__bankRowItem.css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__bankcard']/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b50e1b6-87a8-44fd-859f-e609ec25ce81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi_list_item cw-header__link bankFI__bankRowItem css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      <webElementGuid>b0d6f7a7-6620-4d6a-8200-d808211c2630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>71747a92-8323-48e5-ae69-cf8b47ba0f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/banks/BA-JU4DDFEYHXUH4</value>
      <webElementGuid>cd09807f-4655-46f2-90e8-6adcb86778e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BANK_CARDS|bankRowItem&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|bankRowItem&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|bankRowItem&quot;}</value>
      <webElementGuid>cc5bc3a3-e74d-45ff-8cbe-f070a0a5cca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>3b02f990-4cda-41d6-a070-44f7a2bcb9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>bnk-itm</value>
      <webElementGuid>fe2ea24d-bd3c-4071-954d-40f27a01db76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>22d082fa-7f92-45de-a422-a0d4bd86e8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.Checking ••••48</value>
      <webElementGuid>e5feac7d-58ec-4db0-b6ac-6e81d4ade0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__bankcard&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_bankcards_card css-97ji8w-card_base&quot;]/div[@class=&quot;cw-card__content css-1soddj9-content&quot;]/div[@class=&quot;cw_bankcards_card__fi-list&quot;]/a[@class=&quot;fi_list_item cw-header__link bankFI__bankRowItem css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong&quot;]</value>
      <webElementGuid>767b685f-73a8-4bff-8980-16439ec85758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__bankcard']/div/div/div/a</value>
      <webElementGuid>0492de65-c1d5-45d1-8a14-35a196d37df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get help'])[2]/following::a[1]</value>
      <webElementGuid>747837a3-3485-4966-b753-9118bcf9d813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to banks &amp; cards'])[1]/following::a[2]</value>
      <webElementGuid>8b158a91-40a5-4db1-abe4-64b8eeac9f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/banks/BA-JU4DDFEYHXUH4')]</value>
      <webElementGuid>47f8dbbc-6dce-4a67-a2f6-f4314ae1fcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>cd360de3-7d1d-4627-b370-5b29afcfafcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/banks/BA-JU4DDFEYHXUH4' and (text() = 'PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.Checking ••••48' or . = 'PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.Checking ••••48')]</value>
      <webElementGuid>a248e02a-4962-45a8-b7d5-69ed72dbd46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
