<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bantuan</name>
   <tag></tag>
   <elementGuidId>08623d44-3aa0-4c38-87a6-16cef9adbeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_navbar__primary-item.js_contextualHelp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Bantuan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f680d7b-1d56-4f50-8415-103891952b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/smarthelp/home</value>
      <webElementGuid>c880aec2-b132-416b-8a53-60509419dc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>contextualHelp</value>
      <webElementGuid>513807ad-bd29-4e61-8f9c-835af75b94a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_pressed&quot;}</value>
      <webElementGuid>f87f8837-dba2-461d-9549-59d426ee115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;item_name&quot;:&quot;dw_nav&quot;,&quot;card_type&quot;:&quot;nav_header_help&quot;,&quot;tile_id&quot;:&quot;nav_header_help&quot;,&quot;module&quot;:&quot;header&quot;,&quot;scope&quot;:&quot;tile&quot;,&quot;link_name&quot;:&quot;help&quot;,&quot;default_tab&quot;:&quot;help&quot;}</value>
      <webElementGuid>380ee5d7-8e64-4030-a529-9726f39dda8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__primary-item js_contextualHelp</value>
      <webElementGuid>31a02139-7d3e-4d64-b83a-079058629cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-av-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_loaded&quot;}</value>
      <webElementGuid>1eec7b8d-8231-450b-8578-8fdf8b125b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_shown&quot;}</value>
      <webElementGuid>f0e5cc3d-288b-4f0f-938d-bed1a8de90c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e5ca748-6ec5-4db5-8437-395616977450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bantuan</value>
      <webElementGuid>e593ce29-36c2-4c46-9175-8f461a3e4a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cw_root cw_navbar_enabled&quot;]/div[2]/div[@class=&quot;cw_navbar_drawer cw_drawer_closed&quot;]/div[@class=&quot;cw_navbar cw_navbar--wide&quot;]/div[@class=&quot;cw_navbar__mainnav&quot;]/nav[@class=&quot;cw_navbar__nav&quot;]/ul[@class=&quot;cw_navbar__primary&quot;]/li[5]/a[@class=&quot;cw_navbar__primary-item js_contextualHelp&quot;]</value>
      <webElementGuid>75035e72-a7d4-458a-a644-3cb5afa3cb16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bantuan')]</value>
      <webElementGuid>3d5850cb-b9d6-4a0d-a8cd-0995696dbe0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas'])[1]/following::a[1]</value>
      <webElementGuid>775d7af8-7144-4e0e-8f4d-7f921d7e1d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/following::a[2]</value>
      <webElementGuid>9ef438c0-ab97-4c42-b749-8c931665441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemberitahuan'])[1]/preceding::a[1]</value>
      <webElementGuid>daa474ad-2e72-44d8-b404-2908eaebbd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemberitahuan'])[2]/preceding::a[1]</value>
      <webElementGuid>e7fbe8ac-56e8-4c9a-be20-48ed6b0a9cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bantuan']/parent::*</value>
      <webElementGuid>3228c204-74cf-4dd0-a1cd-741974b38460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/smarthelp/home')]</value>
      <webElementGuid>2f33fcb6-69d2-44bf-97c9-1dc6b3af72f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>80b145d0-00e1-4684-9161-0c9acbe7d01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/smarthelp/home' and (text() = 'Bantuan' or . = 'Bantuan')]</value>
      <webElementGuid>c349fb99-1c3f-4a0b-88c0-730a39565997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
