<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CARD 1</name>
   <tag></tag>
   <elementGuidId>24b2f86d-7a54-460c-8278-403439ebc018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fi_list_item.cw-header__link.cardFI__cardRowItem.css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__bankcard']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79ba0ee8-0787-4749-8e1d-5ab1a06d83c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi_list_item cw-header__link cardFI__cardRowItem css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      <webElementGuid>02a17683-4d3f-4b95-8e9c-4f1a8a02f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>3b1e6f5e-54bd-4664-bb5f-a9ee1321bbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/cards/CC-NW7FNCR3YLVCL</value>
      <webElementGuid>6d2aa04c-f0c5-4864-b21b-1c78ef1a801b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BANK_CARDS|cardRowItem&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|cardRowItem&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|cardRowItem&quot;}</value>
      <webElementGuid>00557292-84db-4caa-ab69-06ae9f26daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>b14b55c5-3786-4b71-9a8c-e841b03af39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>crd-itm</value>
      <webElementGuid>497afcfd-970e-442a-8468-9ffead07b00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e7362bd-7b51-4dc6-b1b0-d0f2e21f704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VisaCredit ••••60</value>
      <webElementGuid>97e7fa51-8fd2-4ed7-a737-ef2f9131f66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__bankcard&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_bankcards_card css-97ji8w-card_base&quot;]/div[@class=&quot;cw-card__content css-1soddj9-content&quot;]/div[@class=&quot;cw_bankcards_card__fi-list&quot;]/a[@class=&quot;fi_list_item cw-header__link cardFI__cardRowItem css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong&quot;]</value>
      <webElementGuid>dd650af7-fac1-443a-a89e-335e537ce366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__bankcard']/div/div/div/a[2]</value>
      <webElementGuid>7cc83682-852c-4691-8dcf-ef8c81057732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.'])[1]/following::a[1]</value>
      <webElementGuid>f9ba0c47-88f4-491d-9dab-fa0a9f844034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/cards/CC-NW7FNCR3YLVCL')]</value>
      <webElementGuid>960a2752-4c8e-4dd3-85a1-7a8ee98ed2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>71c5707c-3f56-42b1-b999-c35fc54350f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/cards/CC-NW7FNCR3YLVCL' and (text() = 'VisaCredit ••••60' or . = 'VisaCredit ••••60')]</value>
      <webElementGuid>fdc91306-bd55-497b-9705-f9c3bf30509e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
