<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get help (1)</name>
   <tag></tag>
   <elementGuidId>7a64dba2-52dc-472b-9f92-69153d04ed81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cw-card.cw-card--borderless.cw_bankcards_card.css-97ji8w-card_base > header.cw-card__header.css-1ao4o69-header > h3.cw-card__header.css-qczjjc-title-text_heading_sm > div.cw-card__header__layout > div.cw-card__header__menu > div.css-kddmuw-overflow_menu_base > menu.css-8cx2tb-list-elevation_level1 > li:nth-of-type(2) > a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__bankcard']/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2bd5f17-285c-4a99-8559-aab3613c6ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cshelp/search?q=Banks%20and%20cards&amp;helpSearchButton=Search</value>
      <webElementGuid>3dc19e40-0f18-4441-967b-b49ad44d3acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>bankcard</value>
      <webElementGuid>185712b7-d5da-4865-98b7-a0eb999508b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>overflowWalletHelp</value>
      <webElementGuid>7393e986-1a88-479f-be1a-8d5a70466de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>3bda0341-39f0-436d-bef5-4b8ad17deab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ae71eff1-1a04-4b68-9948-860d1bd2dca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BANK_CARDS|overflowWalletHelp&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowWalletHelp&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowWalletHelp&quot;}</value>
      <webElementGuid>53d80345-7a3c-4263-bbed-47d450531901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>0060dba2-97ad-4fd5-a087-c169616ee78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowWalletHelp</value>
      <webElementGuid>d0f7f7b7-42a1-4aab-8317-ed65fc7bc892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctx-help-target</name>
      <type>Main</type>
      <value>Banks_and_cards</value>
      <webElementGuid>3aaf3fb9-6200-4685-94c2-f71686dd88c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ed2e51c-1221-403d-b6de-32ae133ec388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>f6e2cf40-4999-461c-8485-1f221420ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>acfa001d-db1c-4e59-965d-4178a11440c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get help</value>
      <webElementGuid>4e3bae90-9e6d-464c-bbe4-2ada6a35ea78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__bankcard&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_bankcards_card css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[2]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>1553aa60-4812-4968-beb1-7823dfc4fc74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__bankcard']/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      <webElementGuid>4ca547b1-b3de-4f26-889e-1257189b1ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Get help')])[2]</value>
      <webElementGuid>61bc7325-4373-4a23-a7d2-ff3932942fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to banks &amp; cards'])[1]/following::a[1]</value>
      <webElementGuid>2c4f59d3-e2a8-4f96-bd82-8173d092aaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bankcard'])[1]/following::a[2]</value>
      <webElementGuid>a95615b3-a3fc-45d7-a685-ce9fad143740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.'])[1]/preceding::a[1]</value>
      <webElementGuid>be9c71e7-b88e-4e05-a308-3e92b6f3df5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cshelp/search?q=Banks%20and%20cards&amp;helpSearchButton=Search')]</value>
      <webElementGuid>c3138bd8-9226-4201-affe-fe48aacc5c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      <webElementGuid>8022652a-7dc9-4d2a-80f0-70ff46bc721b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cshelp/search?q=Banks%20and%20cards&amp;helpSearchButton=Search' and (text() = 'Get help' or . = 'Get help')]</value>
      <webElementGuid>7136b779-0879-4498-9cfa-2e558c2bda8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
