<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get help</name>
   <tag></tag>
   <elementGuidId>6cce05ca-5dfa-454b-b9a4-a34e8af02a2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__balance']/div/header/h3/div/div[2]/div/menu/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d32b68f7-886c-453d-8efe-732ea4bba3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/selfhelp/search?q=balance&amp;helpSearchButton=Search</value>
      <webElementGuid>dccb3fb2-131a-4691-9671-83e8db0d1418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>overflowMenu_balance</value>
      <webElementGuid>623ea45e-6fbe-4dfc-a3c0-d54e7934d6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>83d235e7-7773-44cd-9cdd-e90e5a047e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>b746fa7f-4d61-4df5-b13f-23647d00a2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>06368c00-2c97-4622-829a-317a17328b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BALANCE|overflowBalanceHelp&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowBalanceHelp&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowBalanceHelp&quot;}</value>
      <webElementGuid>e58a1380-1827-4f8c-802e-93b8df96a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>f7395d30-5295-4944-9996-a0f6f2b5ae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowBalanceHelp</value>
      <webElementGuid>39fa3367-f133-45e4-bf3f-625b40521086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctx-help-target</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>38290241-0b6e-4d1a-8263-9f5ddfd14d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a94778ae-da25-4feb-b685-0abb5d0727cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>6abef715-c124-494c-8a09-d4d404682aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1a764d8b-5754-486a-9eb9-a4ad9fac17eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get help</value>
      <webElementGuid>87c5317a-bd9c-45b1-9963-fde09b5b9c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__balance&quot;)/div[@class=&quot;cw-card cw-card--full-click cw_balance css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[3]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>c209637c-2c44-49e8-8d3b-95fb81156cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__balance']/div/header/h3/div/div[2]/div/menu/li[3]/a</value>
      <webElementGuid>0ae96c5e-f7a8-4c45-aab8-b253bd4e678f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get help')]</value>
      <webElementGuid>108ec73b-c31c-4d88-af28-f203e5075305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage currencies'])[1]/following::a[1]</value>
      <webElementGuid>eb297e45-853d-4b37-98f7-34e04b4aff26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to PayPal balance'])[1]/following::a[2]</value>
      <webElementGuid>7cbb1b3c-e3de-49ea-976a-6275c623f528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/preceding::a[1]</value>
      <webElementGuid>683185e6-c3a5-4161-8434-c1f360cf0cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/preceding::a[1]</value>
      <webElementGuid>00588a37-378d-4099-b713-a5d6ec520505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get help']/parent::*</value>
      <webElementGuid>a5746ddb-cef5-4217-aece-4fe7cd236938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/selfhelp/search?q=balance&amp;helpSearchButton=Search')]</value>
      <webElementGuid>04defe70-938e-4ca6-aca4-065f2542a4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//menu/li[3]/a</value>
      <webElementGuid>5c67ff95-5996-4f0a-9372-41930e5e272a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/selfhelp/search?q=balance&amp;helpSearchButton=Search' and (text() = 'Get help' or . = 'Get help')]</value>
      <webElementGuid>e9ae4049-e689-41fb-a238-f40b34c22e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
