<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Go to PayPal balance</name>
   <tag></tag>
   <elementGuidId>d6ab07ae-eb12-4644-b802-1b44ad158537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__balance']/div/header/h3/div/div[2]/div/menu/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2621b068-bf48-48f0-9358-53e7a8182c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/</value>
      <webElementGuid>6ffebd28-5534-41c8-ba1e-d5501eb8c546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>overflowMenu_balance</value>
      <webElementGuid>98146c22-929f-4517-ab7a-ac1a68999127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>overflowBalance</value>
      <webElementGuid>0682e968-ddfb-465e-a87c-ecf3f674db47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f9b72185-b24f-4726-a969-0d86a2d0bb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3ad3e218-ef77-4815-9ec0-f69d585248e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BALANCE|overflowBalance&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowBalance&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowBalance&quot;}</value>
      <webElementGuid>8930005d-1301-4945-bd9c-cb64390a4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>9fb30b44-815f-4bc5-9409-38263e74cdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowBalance</value>
      <webElementGuid>ce898d9d-98d7-434a-a7db-fd98518a4651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>afe92be9-40d2-42ab-95ee-b493addd8852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>955308b3-2035-4f41-8fca-db73ce1f30b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>319999c4-5b78-4593-9998-f31de015281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to PayPal balance</value>
      <webElementGuid>55f0f187-344e-49ac-a9a0-d26a32f2c6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__balance&quot;)/div[@class=&quot;cw-card cw-card--full-click cw_balance css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[1]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>186153f2-f4f4-4a70-8f43-0772704bfd41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__balance']/div/header/h3/div/div[2]/div/menu/li/a</value>
      <webElementGuid>15ee5a2f-8f47-4510-9a5f-3d7495960708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go to PayPal balance')]</value>
      <webElementGuid>4318429d-8dcb-4d13-ad12-e70b22795dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='overflowMenu_balance'])[1]/following::a[1]</value>
      <webElementGuid>82d3a90d-fa84-4e23-8910-20d740134e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal balance'])[1]/following::a[1]</value>
      <webElementGuid>83620a07-bf94-4c4d-9534-44f31db7c8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage currencies'])[1]/preceding::a[1]</value>
      <webElementGuid>de6c07be-0eea-4112-b288-e949af3a1143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get help'])[1]/preceding::a[2]</value>
      <webElementGuid>38579b92-47d6-4bbb-9f1c-5a7a6b6f2be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to PayPal balance']/parent::*</value>
      <webElementGuid>17023d8b-5d8a-4b9b-b88c-24ff17b7d99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/myaccount/money/')])[2]</value>
      <webElementGuid>07b6e732-428f-4534-8dd5-af36a912caf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//menu/li/a</value>
      <webElementGuid>b8c5ebbe-0b59-4dac-bed6-a2e14a236df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/' and (text() = 'Go to PayPal balance' or . = 'Go to PayPal balance')]</value>
      <webElementGuid>9c861bc5-3d4f-41aa-bf6b-70f350e62375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
