<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Go to banks cards</name>
   <tag></tag>
   <elementGuidId>119ae133-5280-477b-b71d-1af7354b6680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cw-card.cw-card--borderless.cw_bankcards_card.css-97ji8w-card_base > header.cw-card__header.css-1ao4o69-header > h3.cw-card__header.css-qczjjc-title-text_heading_sm > div.cw-card__header__layout > div.cw-card__header__menu > div.css-kddmuw-overflow_menu_base > menu.css-8cx2tb-list-elevation_level1 > li > a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__bankcard']/div/header/h3/div/div[2]/div/menu/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1e48f3a-fdde-442b-ac38-35926244e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/</value>
      <webElementGuid>0604719d-32ec-4ae7-9ed0-bab6d8f34aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>bankcard</value>
      <webElementGuid>2e7203e6-db66-4135-9a3a-da251ef84eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>overflowWallet</value>
      <webElementGuid>fca2c749-2b28-4a44-914b-c8723e9aed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f421ea29-f7bc-4959-88c3-b13d5ed33836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>45939d71-e539-4aa0-898d-208b4627b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BANK_CARDS|overflowWallet&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowWallet&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowWallet&quot;}</value>
      <webElementGuid>dd40587f-91f4-43a4-9431-48ea940bbd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>87889191-f4fe-4c73-94f7-872664cf93ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowWallet</value>
      <webElementGuid>e1440dbb-7a33-499b-a046-3ca9b7d0cdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1dcdf3d6-7a45-43a3-a7eb-24d5e2ccd1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>cfe1459f-d96f-4752-a4f7-4d563367ac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f8d29418-0030-4f9a-9a7b-cf8e5d848656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to banks &amp; cards</value>
      <webElementGuid>4f3a9aa5-e528-40e5-8989-becb0511e508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__bankcard&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_bankcards_card css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[1]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>84399509-8c9c-4b47-a3f6-85d9f0a21ea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__bankcard']/div/header/h3/div/div[2]/div/menu/li/a</value>
      <webElementGuid>e84f0b78-2e0f-47c2-9095-ff512653f6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go to banks &amp; cards')]</value>
      <webElementGuid>417ba246-0991-454a-9604-0db9a02138da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bankcard'])[1]/following::a[1]</value>
      <webElementGuid>33605415-9903-473a-b255-252f40dc7cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banks and cards'])[1]/following::a[1]</value>
      <webElementGuid>6726105b-bc21-4a7a-b253-a140c8451bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get help'])[2]/preceding::a[1]</value>
      <webElementGuid>3e3df73a-d87a-42d0-9df9-aaa5c75272b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. BANK NEGARA INDONESIA 1946 (PERSERO) TBK.'])[1]/preceding::a[2]</value>
      <webElementGuid>12894a88-5387-4f0f-ae6a-c487249727f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to banks &amp; cards']/parent::*</value>
      <webElementGuid>b9361fb8-7c8e-4b95-805b-ca2a1202bb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/myaccount/money/')])[6]</value>
      <webElementGuid>3350e6bb-3821-4dbd-8bbd-64c4aec44ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/header/h3/div/div[2]/div/menu/li/a</value>
      <webElementGuid>5c16dee2-4de5-4096-bd49-118ea40f175e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/' and (text() = 'Go to banks &amp; cards' or . = 'Go to banks &amp; cards')]</value>
      <webElementGuid>98556bdc-6230-4c44-8048-569be7b7e060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
