<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kirim dan Minta</name>
   <tag></tag>
   <elementGuidId>79ac7a1b-43da-4b03-b4b1-39fa7aea7a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_navbar__primary-item.js_transfer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kirim dan Minta')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4f0ac64-90d4-4e29-9be7-a86500c493ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer?from=Header</value>
      <webElementGuid>5de5868e-6b7a-4240-a8df-ae9a5174dcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>transfer</value>
      <webElementGuid>9e3875fe-f624-4982-a600-d471ece22064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_pressed&quot;}</value>
      <webElementGuid>dcdcd810-06e8-4242-8784-c032bed72159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;item_name&quot;:&quot;dw_nav&quot;,&quot;product&quot;:&quot;dw_nav&quot;,&quot;link_name&quot;:&quot;payment&quot;,&quot;module&quot;:&quot;header&quot;,&quot;default_tab&quot;:&quot;pay_and_get_paid&quot;,&quot;card_type&quot;:&quot;nav_header_payment&quot;,&quot;tile_id&quot;:&quot;nav_header_payment&quot;,&quot;scope&quot;:&quot;tile&quot;}</value>
      <webElementGuid>d54c39f3-f183-43ce-a4c4-418574e98797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__primary-item js_transfer</value>
      <webElementGuid>5e9ac955-73dd-4ef6-8f7a-4a251958d4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-av-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_loaded&quot;}</value>
      <webElementGuid>c7706afe-4de0-4763-ae8b-9675dc1ba993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_shown&quot;}</value>
      <webElementGuid>41836206-4407-42f3-beee-57ddac0d44aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1f453e4-8ecb-4990-acd3-3e03fb75eec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim dan Minta</value>
      <webElementGuid>73fa07b8-c4d0-4e2f-b147-7560ab92f935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cw_root cw_navbar_enabled&quot;]/div[2]/div[@class=&quot;cw_navbar_drawer cw_drawer_closed&quot;]/div[@class=&quot;cw_navbar cw_navbar--wide&quot;]/div[@class=&quot;cw_navbar__mainnav&quot;]/nav[@class=&quot;cw_navbar__nav&quot;]/ul[@class=&quot;cw_navbar__primary&quot;]/li[2]/a[@class=&quot;cw_navbar__primary-item js_transfer&quot;]</value>
      <webElementGuid>07928719-1c7b-4e6f-a71d-221d1cebf487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kirim dan Minta')]</value>
      <webElementGuid>1a09c9ce-e9da-401d-b7cb-cf2981018974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel Kontrol'])[1]/following::a[1]</value>
      <webElementGuid>0586b541-1c9a-4e8d-b4cc-dc1d7b159c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::a[3]</value>
      <webElementGuid>062440b7-aa37-42f7-9a6d-c283bbf9157f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/preceding::a[1]</value>
      <webElementGuid>b5d08c37-331b-4091-b0ec-4311f81055ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas'])[1]/preceding::a[2]</value>
      <webElementGuid>6f994ac3-76ab-478d-ab9d-b3a39192257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim dan Minta']/parent::*</value>
      <webElementGuid>96394120-2a8f-4158-9655-20a527105f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/transfer?from=Header')]</value>
      <webElementGuid>fcd3aca2-c224-4e39-bb9a-b4531fb20a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>aa0d154e-bd6f-46f5-a77a-bd536e593f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer?from=Header' and (text() = 'Kirim dan Minta' or . = 'Kirim dan Minta')]</value>
      <webElementGuid>ff1e1318-ae8e-4973-a4b3-b90169f5b092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
