<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link a Card or Bank</name>
   <tag></tag>
   <elementGuidId>7afc4aff-b815-4ad9-8e8d-8c3d9388c5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bankCardLinkBankOrCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bankCardLinkBankOrCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffc12c0a-d4f7-4c4c-9c1b-1f3e88f85c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_bankcards_card__footer css-1caaugt-links_base-text_body_strong</value>
      <webElementGuid>2c25427f-eeae-4b01-866b-ad09a657b577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>d70fb122-af00-43d2-ae2c-4ddc61bc3214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/accounts/new?referrer=summary&amp;fptiSource=add_fi_link</value>
      <webElementGuid>6e63e042-700a-4fb5-a359-e48f89e5d84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>LinkBankOrCard</value>
      <webElementGuid>d6491ebe-d3fc-443c-9a93-1c379d581938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BANK_CARDS|LinkBankOrCard&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|LinkBankOrCard&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|LinkBankOrCard&quot;}</value>
      <webElementGuid>64b36415-6883-4884-8983-b5c8735d5d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>a09d7572-65df-42f3-94ed-cc9d6fcd5cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bankCardLinkBankOrCard</value>
      <webElementGuid>047b5e1b-9039-4326-9b57-26dd9a6a8a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b44f9f37-980d-4505-a3b1-8ec266788488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link a Card or Bank</value>
      <webElementGuid>41e8dee6-954e-42c8-893e-0de8010a052c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankCardLinkBankOrCard&quot;)</value>
      <webElementGuid>d76e8de7-b58f-4e2a-8011-c37e89197790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bankCardLinkBankOrCard']</value>
      <webElementGuid>a76f8708-8013-4889-8f93-4ed922201bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__bankcard']/div/footer/div/a</value>
      <webElementGuid>eefb0817-399d-468a-937f-c4f1a2c70fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Link a Card or Bank')]</value>
      <webElementGuid>0e8170b8-2b54-4d77-9534-96c1bb4091e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa'])[1]/following::a[1]</value>
      <webElementGuid>04832f99-1422-49ae-90f3-ac0895e698c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::a[1]</value>
      <webElementGuid>9192fa78-340a-485d-86e7-ed0f8fad9de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>5b706797-27d8-45c5-bd4b-432228e7f224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link a Card or Bank']/parent::*</value>
      <webElementGuid>160f3f98-2449-4a1f-9226-7095b30bc9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/accounts/new?referrer=summary&amp;fptiSource=add_fi_link')]</value>
      <webElementGuid>4dc74c1a-dd24-48c5-8dac-79aa1009cc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/a</value>
      <webElementGuid>19d49527-1b83-4b46-b263-acb0c9d510a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/accounts/new?referrer=summary&amp;fptiSource=add_fi_link' and @id = 'bankCardLinkBankOrCard' and (text() = 'Link a Card or Bank' or . = 'Link a Card or Bank')]</value>
      <webElementGuid>1d33fde9-f586-4fc3-a0f6-9c001f155e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
