<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Log Out</name>
   <tag></tag>
   <elementGuidId>4a65a6e4-3d43-41a4-b2e1-b03026a57a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e9bcfb9-a58d-4167-b883-6a4f51391e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__secondary-item cw_navbar__secondary-item--text cw_navbar_logout</value>
      <webElementGuid>fffdadb2-8832-4d57-84f5-431338bee010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signout</value>
      <webElementGuid>749d7f0c-083b-45fa-92ff-a72683f8041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-logout</value>
      <webElementGuid>825e8849-162b-47e7-a8b7-29a9b4c4d606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>header-logout</value>
      <webElementGuid>c6f27ea5-62b6-44d4-8e29-07182a5b95d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>header-logout</value>
      <webElementGuid>b2df18fe-363e-4a08-aa0e-3bc98013ce7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:header</value>
      <webElementGuid>0c209811-6f3b-4ee4-9d43-84db23b5e65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>header-logout</value>
      <webElementGuid>5beef26e-60df-44eb-91a1-0646ee40b475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>16e93ffe-2420-4771-ba95-38e3c819e563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out</value>
      <webElementGuid>ae1572f5-4477-4d36-8c66-dea7ae069820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-logout&quot;)</value>
      <webElementGuid>93722ed5-d231-48f6-bef1-9f122e4bb663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header-logout']</value>
      <webElementGuid>853a7705-51d2-467c-9977-bced03d1685e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log Out')])[2]</value>
      <webElementGuid>2e42c6bb-742e-4882-ae58-8f24bb395ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[2]/following::a[1]</value>
      <webElementGuid>ba0e0af8-7260-42e3-89f0-34e5e6b5a7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Pesan'])[1]/following::a[2]</value>
      <webElementGuid>b00f7b3d-f8a2-487c-809a-dee58ba72f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::a[1]</value>
      <webElementGuid>ff981985-9d4d-4572-a75c-03da868ee0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/preceding::a[1]</value>
      <webElementGuid>151da08b-2277-4b24-a5c3-17c6733ad71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/signout')])[2]</value>
      <webElementGuid>29b2079a-8759-48eb-a4c5-45815c5b92bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>72e6f06e-905f-4294-91b1-ccc5bca4881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signout' and @id = 'header-logout' and @name = 'header-logout' and (text() = 'Log Out' or . = 'Log Out')]</value>
      <webElementGuid>58789982-7f8b-473b-8ee3-89b25b96094c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
