<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manage contacts</name>
   <tag></tag>
   <elementGuidId>1d1e1938-b486-45e2-ba33-00a5a4fc10cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cw-card.cw-card--borderless.cw_contacts__card.css-97ji8w-card_base > header.cw-card__header.css-1ao4o69-header > h3.cw-card__header.css-qczjjc-title-text_heading_sm > div.cw-card__header__layout > div.cw-card__header__menu > div.css-kddmuw-overflow_menu_base > menu.css-8cx2tb-list-elevation_level1 > li > a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__contacts']/div/header/h3/div/div[2]/div/menu/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d628d607-45f4-4377-9324-40391775f764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer/homepage/contact-list?from=SUM-QuickSend-Menu</value>
      <webElementGuid>9582f2af-7a72-4ac6-90a4-b1030286d1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>sendagain_overflowMenu</value>
      <webElementGuid>afb7b310-1100-4153-881b-2723fc9f35f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>overflowManageContacts</value>
      <webElementGuid>db03918f-344a-430f-b56b-0d0ec06e2bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>298176ca-2abd-46bf-a89a-138b2ec072cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d398ca69-ada9-44f2-83df-7ec6c60e95c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;CONTACTS|overflowManageContacts&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowManageContacts&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowManageContacts&quot;}</value>
      <webElementGuid>87ec9087-80b5-44c9-8be6-e481a742b420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>f2ee19bb-2d9c-47d5-ac50-32303768c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowManageContacts</value>
      <webElementGuid>68c1b6dd-95bf-45e6-bb69-f1256a29e033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>675e9f04-91fb-4c34-9fbd-047765e9ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>99a76fa4-eb67-4622-b7ea-d6d151a959b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fdd7d011-9a0d-4336-a868-bb13f018de0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage contacts</value>
      <webElementGuid>316e872c-2ced-4e57-8e87-a1842812cb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__contacts&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_contacts__card css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[1]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>1741a293-731f-4b75-9bf9-247d37574049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__contacts']/div/header/h3/div/div[2]/div/menu/li/a</value>
      <webElementGuid>6c0187de-f169-4799-9b0d-62e978660207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage contacts')]</value>
      <webElementGuid>cbc87256-b2f2-4439-b464-0dac25853b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sendagain_overflowMenu'])[1]/following::a[1]</value>
      <webElementGuid>e7ed0e03-086a-44d3-a6e6-525f96abf8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send again'])[1]/following::a[1]</value>
      <webElementGuid>20679c4a-d801-40e0-a2b5-5e2d4959b1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to others'])[1]/preceding::a[1]</value>
      <webElementGuid>e6b07533-55ea-45b3-b6ee-838d2a6dea42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[3]/preceding::a[2]</value>
      <webElementGuid>5958f1aa-d012-4f2b-82c2-d507e5f5ebaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage contacts']/parent::*</value>
      <webElementGuid>f162a60e-6143-4d82-acbe-a626a2061cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/transfer/homepage/contact-list?from=SUM-QuickSend-Menu')]</value>
      <webElementGuid>b6b1bbda-f439-46dc-b76b-0a2e9689bb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/header/h3/div/div[2]/div/menu/li/a</value>
      <webElementGuid>cb448bab-4263-43eb-965a-5385c7d880bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer/homepage/contact-list?from=SUM-QuickSend-Menu' and (text() = 'Manage contacts' or . = 'Manage contacts')]</value>
      <webElementGuid>b2123fd2-d8df-4faf-bc6d-bf44f5c0e650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
