<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu Contacts</name>
   <tag></tag>
   <elementGuidId>bb16f178-abad-451c-a3c0-8910fb90ef19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;sendagain_overflowMenu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='sendagain_overflowMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8588ff26-5d5a-42e3-982f-0e902fcf55d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>icon-button_3.6.8</value>
      <webElementGuid>969b7a8f-66af-40de-b55f-cc3dd2f765c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1rie9kd-icon-button_base-tertiary</value>
      <webElementGuid>cc0ded38-0f18-4708-92f9-48917870642c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe7fd90c-6a81-430b-94fa-762e9946a294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sendagain_overflowMenu</value>
      <webElementGuid>4e74790b-90ee-4685-99cf-f3adcf2b9786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad442253-f120-4c21-b957-f856f29781b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84a34498-c8e1-42dd-9b96-341f41bc4c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b65a7072-a401-47ee-ae5d-7fac6adf923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2c50b31e-5beb-4f69-8966-6ac09bf05a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sendagain_overflowMenu</value>
      <webElementGuid>d9b45640-b46c-41ba-8d0d-cc0a5683ff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__contacts&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_contacts__card css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/button[@class=&quot;css-1rie9kd-icon-button_base-tertiary&quot;]</value>
      <webElementGuid>fdcd1d9c-196e-420f-9781-34157913275a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='sendagain_overflowMenu']</value>
      <webElementGuid>d00081cf-02bd-450e-9322-c728ee72e08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__contacts']/div/header/h3/div/div[2]/div/button</value>
      <webElementGuid>639a6408-a62a-4a54-a56a-a02187a81541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send again'])[1]/following::button[1]</value>
      <webElementGuid>24560081-7648-48a9-b0fe-08c8c0d25950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/following::button[1]</value>
      <webElementGuid>17656a05-bde6-4e05-98aa-99cb2b1cffe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage contacts'])[1]/preceding::button[1]</value>
      <webElementGuid>f6363b1d-afaa-4ddb-832d-d9308f2f4c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/header/h3/div/div[2]/div/button</value>
      <webElementGuid>bcf8a4ff-7959-4bde-b4ad-f0b91092b054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'sendagain_overflowMenu' and (text() = 'sendagain_overflowMenu' or . = 'sendagain_overflowMenu')]</value>
      <webElementGuid>8d63a617-aba7-4d9f-8b1d-ae5b3225236b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
