<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Panel Kontrol</name>
   <tag></tag>
   <elementGuidId>5b772159-2e03-4b91-9703-e88eabc20604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_navbar__primary-item.js_newSummary.cw_navbar__primary-item--selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Panel Kontrol')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dbad8f4-8535-44b8-9c3d-c2601cf95861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/summary</value>
      <webElementGuid>a3118b54-7392-43d0-9338-4c0219e718d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>newSummary</value>
      <webElementGuid>58849d5a-d36f-425f-8beb-e0cdda5e8460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_pressed&quot;}</value>
      <webElementGuid>493bb76c-49c9-43a5-a9ee-7412d0222766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;item_name&quot;:&quot;dw_nav&quot;,&quot;link_name&quot;:&quot;dashboard&quot;,&quot;default_tab&quot;:&quot;Dashboard&quot;,&quot;product&quot;:&quot;dw_nav&quot;,&quot;module&quot;:&quot;header&quot;,&quot;card_type&quot;:&quot;nav_header_dashboard&quot;,&quot;tile_id&quot;:&quot;nav_header_dashboard&quot;,&quot;scope&quot;:&quot;tile&quot;}</value>
      <webElementGuid>84971c91-664a-49b2-9253-1186329f0cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__primary-item js_newSummary cw_navbar__primary-item--selected</value>
      <webElementGuid>2e226b50-4350-4dfb-b4e5-e9322c85b064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-av-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_loaded&quot;}</value>
      <webElementGuid>ab6c7a69-acf3-461f-badb-ad77938c558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_shown&quot;}</value>
      <webElementGuid>57e96cee-6551-4cab-86f1-6ef398065c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd6009b5-9e8d-4e64-b4d4-f723f972a376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panel Kontrol</value>
      <webElementGuid>688db72b-5725-4ac7-b8b2-da40defbe5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cw_root cw_navbar_enabled&quot;]/div[2]/div[@class=&quot;cw_navbar_drawer cw_drawer_closed&quot;]/div[@class=&quot;cw_navbar cw_navbar--wide&quot;]/div[@class=&quot;cw_navbar__mainnav&quot;]/nav[@class=&quot;cw_navbar__nav&quot;]/ul[@class=&quot;cw_navbar__primary&quot;]/li[1]/a[@class=&quot;cw_navbar__primary-item js_newSummary cw_navbar__primary-item--selected&quot;]</value>
      <webElementGuid>42c8b4df-785e-41a1-bee1-1446fb52e27c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Panel Kontrol')]</value>
      <webElementGuid>3b5cbb32-685a-4423-a6d0-0cdc6b3a62a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::a[2]</value>
      <webElementGuid>b48fa37e-e351-4a0c-afcc-5bb45084ce72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::a[3]</value>
      <webElementGuid>a3e6acc7-f6f9-43c1-855e-32542bd7ce57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim dan Minta'])[1]/preceding::a[1]</value>
      <webElementGuid>3dda69de-1ec4-4f5f-b1f2-eec4d0b0589d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/preceding::a[2]</value>
      <webElementGuid>a86056ea-9db5-43fb-8f09-2c8409a71ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Panel Kontrol']/parent::*</value>
      <webElementGuid>fd185e5e-78a8-49fa-9fec-25d4e79fdee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/myaccount/summary')])[2]</value>
      <webElementGuid>758332fe-1de1-47bd-b237-403b6c252b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>53c3b9dd-bce4-48c8-85e6-bb556be8500b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/summary' and (text() = 'Panel Kontrol' or . = 'Panel Kontrol')]</value>
      <webElementGuid>0c057896-5dc8-46e5-9e3f-e1d7e416a6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
