<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayPal balance</name>
   <tag></tag>
   <elementGuidId>2926444b-6ae7-41de-b838-dd46341c0317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__balance']/div/header/h3/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bcbe0fc0-a428-4283-a2a1-7eb6eb88fd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong</value>
      <webElementGuid>646d43cc-f483-45b5-acce-3ebe9ad96e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>8fd91448-62a3-45a2-9050-45bb1d6a817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/</value>
      <webElementGuid>553bdf66-f28f-4ced-83d4-74b2bce887ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;domain_status&quot;:&quot;DEFAULT&quot;}</value>
      <webElementGuid>b9a80d8b-3158-4072-a108-2920daaa67e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>balance_header</value>
      <webElementGuid>6888403d-efeb-4a58-a872-4ff693732c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>76fce1c3-ac7c-4efd-ad71-03b38e9289b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PayPal balance</value>
      <webElementGuid>56d07042-3583-4792-a9e2-facd59225cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__balance&quot;)/div[@class=&quot;cw-card cw-card--full-click cw_balance css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__content&quot;]/a[@class=&quot;css-1chx7ec-links_base-text_body_strong-secondary-text_body_strong&quot;]</value>
      <webElementGuid>a44b5d87-c916-40ae-8081-54816f3a59a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__balance']/div/header/h3/div/div/a</value>
      <webElementGuid>34c3836f-5a91-4299-8a55-308bac0cc208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PayPal balance')]</value>
      <webElementGuid>2433a1cd-c464-4866-afae-c50940509c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::a[1]</value>
      <webElementGuid>3d48c314-1b44-4e73-b34c-ee17b593f141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal: Summary'])[2]/following::a[1]</value>
      <webElementGuid>275c009b-7933-491b-92ae-efe75fe66512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='overflowMenu_balance'])[1]/preceding::a[1]</value>
      <webElementGuid>f9e3d652-e84e-4c7a-893f-7d4415ef1e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to PayPal balance'])[1]/preceding::a[1]</value>
      <webElementGuid>9121b548-e2d4-4ee3-9076-8c7fc29d65a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PayPal balance']/parent::*</value>
      <webElementGuid>aa88a5b8-1f5a-44b2-a531-563d261b5da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/')]</value>
      <webElementGuid>3447440f-ee2d-43c4-a28e-0a8d3fa29a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/div/a</value>
      <webElementGuid>afe7c608-7452-4d24-b60c-6e510e4289bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/' and (text() = 'PayPal balance' or . = 'PayPal balance')]</value>
      <webElementGuid>7c045968-12e9-4a19-bb82-f16cb5d9702c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
