<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayPal Logo</name>
   <tag></tag>
   <elementGuidId>158d7817-a4df-488f-a1a7-1ccbe4caf13e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Dashboard&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-ppLogo']/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1edf4d8e-58c0-4b6f-a78f-79200e1135d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.paypalobjects.com/paypal-ui/logos/svg/paypal-mark-monotone-transparent.svg</value>
      <webElementGuid>53664d41-4b95-4a3a-b7b7-aa56afc597de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>7c62b133-1663-418d-8350-d847de249c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>logo-icon</value>
      <webElementGuid>8a175480-c473-4786-8118-37a123c8e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-ppLogo&quot;)/span[@class=&quot;cw-icon__svg cw-icon__size_md&quot;]/img[1]</value>
      <webElementGuid>ce78ce06-aba8-4517-9078-4c9f9d3d720f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='header-ppLogo']/span/img</value>
      <webElementGuid>2e9845ab-243e-47d3-bb62-6ef970738402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dashboard']</value>
      <webElementGuid>bfc818aa-10ea-44de-ac45-7a174443f571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b345b4de-aa1d-4753-ae43-7b4451a77a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.paypalobjects.com/paypal-ui/logos/svg/paypal-mark-monotone-transparent.svg' and @alt = 'Dashboard']</value>
      <webElementGuid>8f0f0f06-101c-42c9-8c28-8bf1b79d0486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
