<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pemberitahuan</name>
   <tag></tag>
   <elementGuidId>5e67df3b-ef3d-4578-b372-e14b2a1689de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-notifications</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-notifications']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>494ed05c-ab9c-448e-b67e-4ed2c730fcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7b80c13b-0be8-4cf4-954e-8dede7144930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-notifications</value>
      <webElementGuid>937e327c-01d7-4491-80c4-334dfa8cb0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>header-notifications</value>
      <webElementGuid>ddcc4bbd-82c4-4849-867b-d11c0f3e4686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_dw2_notifications vx_isCritical js_notifications js_notificationDesktopBtn cw_popover-trigger</value>
      <webElementGuid>b1de6de1-b20d-4634-a5d9-6f01e8860fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-autodisplay</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e8d6d12-5b12-43c3-a33e-701981165dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-id</name>
      <type>Main</type>
      <value>notifications-popover</value>
      <webElementGuid>f9d1f342-d94e-48f2-936d-9a8897b3c2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-offset</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>8790d0dd-aa32-4bd6-bb99-9497beebb1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagename</name>
      <type>Main</type>
      <value>main:notifications::toggle</value>
      <webElementGuid>a0b58eed-956c-4685-bf08-16127c2282b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-pagename-show</name>
      <type>Main</type>
      <value>main:notifications:toggle</value>
      <webElementGuid>f1e0a2d9-7db3-4f30-849f-05f62d3b15ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popover-pagename-hide</name>
      <type>Main</type>
      <value>main:notifications:toggle</value>
      <webElementGuid>f5b1bf48-98b7-41ce-9604-8808bede2598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>header-notifications</value>
      <webElementGuid>6e1abef0-0c62-4c03-87da-06215ef045f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;page&quot;:&quot;main:walletweb:summary:main:notificationcenter&quot;,&quot;pgrp&quot;:&quot;main:walletweb:summary::main&quot;,&quot;pros&quot;:&quot;0&quot;,&quot;vers&quot;:&quot;customer&quot;,&quot;pgtf&quot;:&quot;Nodejs&quot;,&quot;comp&quot;:&quot;commonutilsnodeserv&quot;,&quot;rsta&quot;:&quot;id_ID&quot;,&quot;ccpg&quot;:&quot;ID&quot;,&quot;cust&quot;:&quot;5TPGRCBX8MPNU&quot;,&quot;lcid&quot;:&quot;f87385657600d&quot;,&quot;msgcd&quot;:0}</value>
      <webElementGuid>30acc223-d7fa-4b6b-beaf-07394e074643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;pglk&quot;:&quot;main:walletweb:summary:main:notificationcenter|badgeClick&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main:notificationcenter|badgeClick&quot;,&quot;pros&quot;:&quot;0&quot;,&quot;link&quot;:&quot;notificationBadge&quot;}</value>
      <webElementGuid>3057a8e3-2859-4fd4-951a-dfa40a8e5d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>93bb12c3-a190-45de-bb73-400e6175a56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d589de6e-1f8e-43b5-9565-cdca8a014ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  
Pemberitahuan0(function () { const elem = document.querySelector(&quot;#notification-center-badge&quot;);  const item = window.sessionStorage.getItem(&quot;PP_NC&quot;); if (elem &amp;&amp; item) { const parts = item.split(':'); const savedUserKey = parts[0]; const savedBadge = parts[1]; if (savedUserKey === &quot;1447af215ba5e1e85692cdf0f14c08745a384f787558190f8b9e6ea0e6ab9c4773e92fda126bf59bdd29e6ac1f27384b858037463507432d9fcf4851e3e81c52&quot; &amp;&amp; savedBadge !== '0') { elem.innerHTML = savedBadge; elem.style.display = ''; } } })();Pemberitahuan</value>
      <webElementGuid>d8a2918b-34ef-4f59-ad27-88d6d6f30f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-notifications&quot;)</value>
      <webElementGuid>9969b6bb-0bdb-4088-a0f3-c07b9f9e2146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header-notifications']</value>
      <webElementGuid>00cb190c-3910-4f55-80b3-97537638f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/following::a[1]</value>
      <webElementGuid>a2fad4c0-215b-4240-9866-da058ea82cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas'])[1]/following::a[2]</value>
      <webElementGuid>ad413501-ebfd-4227-bfd0-d2d19da0b635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>3e25cda0-57c8-4d05-9b20-8ea5a2ad65f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>80b4a488-6901-49ca-bf4a-066036dccce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'header-notifications' and (text() = concat(&quot;
  
Pemberitahuan0(function () { const elem = document.querySelector(&quot;#notification-center-badge&quot;);  const item = window.sessionStorage.getItem(&quot;PP_NC&quot;); if (elem &amp;&amp; item) { const parts = item.split(&quot; , &quot;'&quot; , &quot;:&quot; , &quot;'&quot; , &quot;); const savedUserKey = parts[0]; const savedBadge = parts[1]; if (savedUserKey === &quot;1447af215ba5e1e85692cdf0f14c08745a384f787558190f8b9e6ea0e6ab9c4773e92fda126bf59bdd29e6ac1f27384b858037463507432d9fcf4851e3e81c52&quot; &amp;&amp; savedBadge !== &quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;) { elem.innerHTML = savedBadge; elem.style.display = &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;; } } })();Pemberitahuan&quot;) or . = concat(&quot;
  
Pemberitahuan0(function () { const elem = document.querySelector(&quot;#notification-center-badge&quot;);  const item = window.sessionStorage.getItem(&quot;PP_NC&quot;); if (elem &amp;&amp; item) { const parts = item.split(&quot; , &quot;'&quot; , &quot;:&quot; , &quot;'&quot; , &quot;); const savedUserKey = parts[0]; const savedBadge = parts[1]; if (savedUserKey === &quot;1447af215ba5e1e85692cdf0f14c08745a384f787558190f8b9e6ea0e6ab9c4773e92fda126bf59bdd29e6ac1f27384b858037463507432d9fcf4851e3e81c52&quot; &amp;&amp; savedBadge !== &quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;) { elem.innerHTML = savedBadge; elem.style.display = &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;; } } })();Pemberitahuan&quot;))]</value>
      <webElementGuid>9c9fc977-02a5-472c-9f5d-f9f35eb244ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
