<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search (Transfer Funds)</name>
   <tag></tag>
   <elementGuidId>7e532847-73aa-42b8-8ad5-4cba040fc7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw-contact__avatar-link.cw_tile__contacts-contactSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__contacts']/div/div/div/div/div/div/ul/li[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca69c218-f487-4f64-b30d-491ed9a9d419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;CONTACTS|cw_tile__contacts-contactSearch&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|cw_tile__contacts-contactSearch&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|cw_tile__contacts-contactSearch&quot;}</value>
      <webElementGuid>f964d263-5739-443a-8d38-db3a95850b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>7776cb6b-818a-44b9-873d-10cb7170f45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer/homepage/send?from=SUM-QuickSend</value>
      <webElementGuid>013c08e8-864b-46ab-bb12-40e3baa9971d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw-contact__avatar-link cw_tile__contacts-contactSearch</value>
      <webElementGuid>c06f60fc-c47d-4dc3-9cc1-294e45a9e3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>contact-search</value>
      <webElementGuid>34ba1e49-9e9e-4fce-9f74-204da9ae6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>aria-contact-search</value>
      <webElementGuid>ba707fcc-5ccf-4ca9-9d4e-cbe7c040d9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8b409548-fe3c-4fba-b854-1260379ef31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>93a77848-824c-4028-9c01-baf7b1cb9ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__contacts&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_contacts__card css-97ji8w-card_base&quot;]/div[@class=&quot;cw-card__content css-1soddj9-content&quot;]/div[@class=&quot;cw-contacts__body&quot;]/div[@class=&quot;cw-contacts__topContacts-list css-tnax4s-horizontal_scroll_base&quot;]/div[@class=&quot;css-36pk32-page_container&quot;]/div[@class=&quot;css-1baea8v-page&quot;]/ul[@class=&quot;css-1g2endo-item_list-item_list_desktop&quot;]/li[@class=&quot;css-19gw1j0-item-desktop&quot;]/div[@class=&quot;cw-contact__avatar-container&quot;]/a[@class=&quot;cw-contact__avatar-link cw_tile__contacts-contactSearch&quot;]</value>
      <webElementGuid>24cc9777-b9c9-4146-8b30-ab55129aaf70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__contacts']/div/div/div/div/div/div/ul/li[2]/div/a</value>
      <webElementGuid>e5a8ac85-bd94-4025-b076-054e9b03994d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[3]/following::a[1]</value>
      <webElementGuid>dceba9aa-7fdf-451e-8b38-209e2ca3072b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to others'])[1]/following::a[2]</value>
      <webElementGuid>c2c80ad9-2566-4e33-91c7-c13289ab826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banks and cards'])[1]/preceding::a[1]</value>
      <webElementGuid>17e5f7a0-ff5a-4675-afff-7d4afa17e498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/myaccount/transfer/homepage/send?from=SUM-QuickSend')])[3]</value>
      <webElementGuid>92b03398-3748-4272-9c1e-df8a18a65571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>8f675b14-bc15-4283-82f7-7e714d3e2b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer/homepage/send?from=SUM-QuickSend' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>19aa1718-fabb-4675-9d07-466b4d3a2850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
