<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send to others</name>
   <tag></tag>
   <elementGuidId>aea027c4-aa47-40d6-8b62-0a2c3d0658a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cw-card.cw-card--borderless.cw_contacts__card.css-97ji8w-card_base > header.cw-card__header.css-1ao4o69-header > h3.cw-card__header.css-qczjjc-title-text_heading_sm > div.cw-card__header__layout > div.cw-card__header__menu > div.css-kddmuw-overflow_menu_base > menu.css-8cx2tb-list-elevation_level1 > li:nth-of-type(2) > a.css-5mexf4-list_item-text_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__contacts']/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f45e723-da27-4523-aad1-72fc544533a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer/homepage/send?from=SUM-QuickSend-Menu</value>
      <webElementGuid>18dce85f-8f5e-4c14-b1a2-9988ea1d54cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>sendagain_overflowMenu</value>
      <webElementGuid>10cf1aa9-4492-4f31-987e-bc0df8519127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>overflowSendElse</value>
      <webElementGuid>aad9d7af-4c44-4adf-a686-193fede30ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>5150a856-a49f-4361-b8a4-334b8efb473f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>355332ed-03a3-4340-896d-12b93dbad11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;CONTACTS|overflowSendElse&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|overflowSendElse&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|overflowSendElse&quot;}</value>
      <webElementGuid>c0ecd073-1ca4-4ca8-ba05-18c11faa8cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>d357627e-0e33-41cf-9fe5-dc4fabf2a9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>overflowSendElse</value>
      <webElementGuid>77e2c4dc-8206-4c44-9977-3dfad58d7c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf157e4a-3f9b-4c87-899c-5cc8b4526b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5mexf4-list_item-text_body</value>
      <webElementGuid>0f94d2ba-8c08-4a35-ac38-f9b751e4f356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>51657ec3-7593-4f24-8b08-311483a86682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send to others</value>
      <webElementGuid>c27e4dc4-37d3-4c27-b6c8-b4b5136616e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__contacts&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_contacts__card css-97ji8w-card_base&quot;]/header[@class=&quot;cw-card__header css-1ao4o69-header&quot;]/h3[@class=&quot;cw-card__header css-qczjjc-title-text_heading_sm&quot;]/div[@class=&quot;cw-card__header__layout&quot;]/div[@class=&quot;cw-card__header__menu&quot;]/div[@class=&quot;css-kddmuw-overflow_menu_base&quot;]/menu[@class=&quot;css-8cx2tb-list-elevation_level1&quot;]/li[2]/a[@class=&quot;css-5mexf4-list_item-text_body&quot;]</value>
      <webElementGuid>5f418e0b-aeb6-4103-aedb-c84622849aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__contacts']/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      <webElementGuid>a364872a-7980-48fa-81b1-96dd3d2f904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Send to others')]</value>
      <webElementGuid>77f68fa5-72d5-4c69-9fa0-9bebe8301e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage contacts'])[1]/following::a[1]</value>
      <webElementGuid>bb6db178-d5ae-4380-894d-8c17b77e6372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sendagain_overflowMenu'])[1]/following::a[2]</value>
      <webElementGuid>489b9ef3-c5bd-484f-9839-cc4f4e1e63ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[3]/preceding::a[1]</value>
      <webElementGuid>b35596f5-1a6d-4030-ba30-319e036b3b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[2]</value>
      <webElementGuid>088f65e1-66e8-4cd6-a09a-5f42cfcf1327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send to others']/parent::*</value>
      <webElementGuid>55837ed8-27b4-437a-ba6c-52cc553e5191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/transfer/homepage/send?from=SUM-QuickSend-Menu')]</value>
      <webElementGuid>774c91ee-0e5d-4de3-811a-d322c2f35079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/header/h3/div/div[2]/div/menu/li[2]/a</value>
      <webElementGuid>3f65f0db-3710-4811-a948-0a8888ea5116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer/homepage/send?from=SUM-QuickSend-Menu' and (text() = 'Send to others' or . = 'Send to others')]</value>
      <webElementGuid>a68958ca-e895-438b-a7b3-b6328c947eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
