<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show all activities</name>
   <tag></tag>
   <elementGuidId>8048e5ae-3cd2-403a-9e7b-97ea2ad3b7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.spf-1caaugt-links_base-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer-link']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be51c80d-e3ec-4386-9571-f8ae18bc0267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> spf-1caaugt-links_base-text_body_strong</value>
      <webElementGuid>906cb76d-1cc7-44a9-a160-c01cfcd52a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.6.4</value>
      <webElementGuid>5950d657-1b4a-4912-9aec-6309477e1fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bce25ba7-7ea3-4906-8fc7-93cb733d32ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4d2f27d9-8945-481c-af1f-c247bea76248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show all</value>
      <webElementGuid>b9afc9b6-cf52-4454-a8a2-45b2fd511dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-link&quot;)/a[@class=&quot;spf-1caaugt-links_base-text_body_strong&quot;]</value>
      <webElementGuid>e7cbee48-0a21-41a9-9060-0be97bfe5277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer-link']/a</value>
      <webElementGuid>c6c1d1b7-2d31-4daf-bf6c-7ead91ca8caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Show all')]</value>
      <webElementGuid>4ec6e6c2-0fa3-42b3-869e-46dc5ff80302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−Rp 730.363 IDR'])[2]/following::a[2]</value>
      <webElementGuid>77d35551-77d4-400c-922b-d2dc3555592a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. BANK JASA JAKARTA'])[2]/following::a[2]</value>
      <webElementGuid>323d7ca9-12d4-43e2-b200-d3590bda7639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::a[1]</value>
      <webElementGuid>62ab00fc-0330-4f96-89ec-72969a9f5503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send again'])[1]/preceding::a[1]</value>
      <webElementGuid>07cfc4e9-118c-4b39-be28-e12fa43c54c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show all']/parent::*</value>
      <webElementGuid>e2e5824d-cc69-4a38-91b1-b80482d8b47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a</value>
      <webElementGuid>fc33790c-888a-4ca2-8313-1732a56c5956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Show all' or . = 'Show all')]</value>
      <webElementGuid>d276dac0-3689-4e82-adb3-fd004dfc8670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
