<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Test Store (Transfer Funds)</name>
   <tag></tag>
   <elementGuidId>456f66d9-22a1-4f01-8275-8707f3aaa2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw-contact__avatar-link.cw_tile__contacts-contactBubble</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__contacts']/div/div/div/div/div/div/ul/li/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42853319-b0d5-4ba5-bed8-6233cf9e9a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;CONTACTS|cw_tile__contacts-contactBubble&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|cw_tile__contacts-contactBubble&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|cw_tile__contacts-contactBubble&quot;}</value>
      <webElementGuid>6fe01e2c-b401-4745-bfa8-d829ad725cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>c90a5f0c-cffd-49b3-94b7-a975e869923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/transfer/homepage/external/summary?flowContextData=J6PGN5PIESCBUvEyt2_GU9nwC48C6kA-g_U3rbaREQ3gnfbu3UQIohU6TkyJo_n5cAr2qg09Ui4vHpG3g3fxn7D4ajQ1YThXb4sISAAk_6VaOVPRzs1-Jw0NmueTKZ6Gs78jn2lhE1-UxXJ00yCgdRIAHq3m3iBuiEEPuG0RGquJlnlJ</value>
      <webElementGuid>7b834640-2335-43a4-a96f-c74b92cf53bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw-contact__avatar-link cw_tile__contacts-contactBubble</value>
      <webElementGuid>4c381cb8-580b-4ba6-b573-56f2fe41b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>contact_bubble</value>
      <webElementGuid>d0648ef9-51df-41a8-a2bb-f2f1f683ee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5fc8c00f-57df-427a-9b20-526329b76338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Store</value>
      <webElementGuid>c8319eaf-d8b5-45f9-8101-1b6b64f33962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__contacts&quot;)/div[@class=&quot;cw-card cw-card--borderless cw_contacts__card css-97ji8w-card_base&quot;]/div[@class=&quot;cw-card__content css-1soddj9-content&quot;]/div[@class=&quot;cw-contacts__body&quot;]/div[@class=&quot;cw-contacts__topContacts-list css-tnax4s-horizontal_scroll_base&quot;]/div[@class=&quot;css-36pk32-page_container&quot;]/div[@class=&quot;css-1baea8v-page&quot;]/ul[@class=&quot;css-1g2endo-item_list-item_list_desktop&quot;]/li[@class=&quot;css-19gw1j0-item-desktop&quot;]/div[@class=&quot;cw-contact__avatar-container&quot;]/a[@class=&quot;cw-contact__avatar-link cw_tile__contacts-contactBubble&quot;]</value>
      <webElementGuid>3bf9a4ae-e916-4a99-aa79-13d89bea31c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__contacts']/div/div/div/div/div/div/ul/li/div/a</value>
      <webElementGuid>783a6f17-d5d3-41a3-b5d1-0aa232cf5381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to others'])[1]/following::a[1]</value>
      <webElementGuid>33b034df-cf24-46a9-beaa-73128e7886fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage contacts'])[1]/following::a[2]</value>
      <webElementGuid>7e6150bc-73d5-4a5f-9693-e9c847aff05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>fa92197a-fd6c-413c-8a9d-f307c1f77ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/transfer/homepage/external/summary?flowContextData=J6PGN5PIESCBUvEyt2_GU9nwC48C6kA-g_U3rbaREQ3gnfbu3UQIohU6TkyJo_n5cAr2qg09Ui4vHpG3g3fxn7D4ajQ1YThXb4sISAAk_6VaOVPRzs1-Jw0NmueTKZ6Gs78jn2lhE1-UxXJ00yCgdRIAHq3m3iBuiEEPuG0RGquJlnlJ')]</value>
      <webElementGuid>b666b703-810c-4207-9bad-4b3d2c5661c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a</value>
      <webElementGuid>a96b6e05-f162-4b9e-a713-3733789704a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/transfer/homepage/external/summary?flowContextData=J6PGN5PIESCBUvEyt2_GU9nwC48C6kA-g_U3rbaREQ3gnfbu3UQIohU6TkyJo_n5cAr2qg09Ui4vHpG3g3fxn7D4ajQ1YThXb4sISAAk_6VaOVPRzs1-Jw0NmueTKZ6Gs78jn2lhE1-UxXJ00yCgdRIAHq3m3iBuiEEPuG0RGquJlnlJ' and (text() = 'Test Store' or . = 'Test Store')]</value>
      <webElementGuid>d6e8714d-3a86-459a-b1fd-2eafe24eaf04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
