<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transfer Funds</name>
   <tag></tag>
   <elementGuidId>55c64fa5-df49-4728-b3c8-fc38a953a4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_balance__action.css-cghe3x-button_base-text_button_lg-btn_full_width-size_sm-text_button_sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactContainer__balance']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee74f28b-5e53-4944-842f-2eec9ae86b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>800895a0-4d3f-4450-b097-08ac7e711394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_balance__action css-cghe3x-button_base-text_button_lg-btn_full_width-size_sm-text_button_sm</value>
      <webElementGuid>1ef64139-d8dd-4d23-99b7-f6d670dc6f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.4__7.42.2</value>
      <webElementGuid>26792e9f-3e15-490a-a4ea-3904aa478ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>596b454a-9fab-4a40-b709-890de60faba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money/balances/transfer?flow=eyJyZXR1cm5VcmwiOiIvbXlhY2NvdW50L3N1bW1hcnkvIiwiY2FuY2VsVXJsIjoiL215YWNjb3VudC9zdW1tYXJ5LyJ9</value>
      <webElementGuid>255eed53-eef6-4526-8e7d-829724bcd0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>transfer-money-action</value>
      <webElementGuid>121aa0bc-678c-46dd-8d88-5bb24268ad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;link&quot;:&quot;BALANCE|balanceTransferMoney&quot;,&quot;pglk&quot;:&quot;main:walletweb:summary::main|balanceTransferMoney&quot;,&quot;pgln&quot;:&quot;main:walletweb:summary:main|balanceTransferMoney&quot;}</value>
      <webElementGuid>b8a43c6f-9c4c-49c5-b4cd-0f34954125f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>f4780c03-f469-4abf-aa4b-1a1ccebeeb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1f75845-000f-45c3-8b8a-0acceb9f784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Funds</value>
      <webElementGuid>3db9769e-ad30-4a3e-9899-0c34da51ebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactContainer__balance&quot;)/div[@class=&quot;cw-card cw-card--full-click cw_balance css-97ji8w-card_base&quot;]/div[@class=&quot;cw-card__content css-1soddj9-content&quot;]/a[@class=&quot;cw_balance__action css-cghe3x-button_base-text_button_lg-btn_full_width-size_sm-text_button_sm&quot;]</value>
      <webElementGuid>145c48ee-dfcd-473d-b431-0b28383e3aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactContainer__balance']/div/div/a</value>
      <webElementGuid>2a1d726b-52c5-4e0f-aea2-6e990b239717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transfer Funds')]</value>
      <webElementGuid>71b1fd70-45ce-49ce-b9bb-635f97267962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::a[1]</value>
      <webElementGuid>ee044997-624f-4fb3-824d-d8cdf2b84188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get help'])[1]/following::a[1]</value>
      <webElementGuid>6a487bd0-4879-456d-af8a-6dff94231afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent activity'])[1]/preceding::a[1]</value>
      <webElementGuid>86733bd7-39d3-42b7-a068-f0fbac6baf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[1]/preceding::a[1]</value>
      <webElementGuid>eefd70c3-9716-4543-8734-cdd9b6ae1cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer Funds']/parent::*</value>
      <webElementGuid>23f24c73-f9fd-4bff-995e-81fbd593190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money/balances/transfer?flow=eyJyZXR1cm5VcmwiOiIvbXlhY2NvdW50L3N1bW1hcnkvIiwiY2FuY2VsVXJsIjoiL215YWNjb3VudC9zdW1tYXJ5LyJ9')]</value>
      <webElementGuid>8e4d6bc5-0e84-488f-8085-fad5f442ef04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>98fd593d-dd59-41d0-9d40-a59374c85725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money/balances/transfer?flow=eyJyZXR1cm5VcmwiOiIvbXlhY2NvdW50L3N1bW1hcnkvIiwiY2FuY2VsVXJsIjoiL215YWNjb3VudC9zdW1tYXJ5LyJ9' and (text() = 'Transfer Funds' or . = 'Transfer Funds')]</value>
      <webElementGuid>66e13da2-7210-42f4-ae01-2c9c3a3dd52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
