<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wallet</name>
   <tag></tag>
   <elementGuidId>c781b86a-ddbe-48f1-8c9d-29938e498f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cw_navbar__primary-item.js_wallet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Wallet')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92a65ae2-3de0-45ca-903f-bcd6db9882a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/myaccount/money</value>
      <webElementGuid>bca6fc71-102c-40d0-9835-50a6cd8e82bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>wallet</value>
      <webElementGuid>8c93c426-d63d-462b-b9eb-fb532b1f6c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-cl</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_pressed&quot;}</value>
      <webElementGuid>2debef8c-e562-46cd-8183-7b7201da31db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-base</name>
      <type>Main</type>
      <value>{&quot;item_name&quot;:&quot;dw_nav&quot;,&quot;product&quot;:&quot;dw_nav&quot;,&quot;link_name&quot;:&quot;wallet&quot;,&quot;module&quot;:&quot;header&quot;,&quot;default_tab&quot;:&quot;Wallet&quot;,&quot;card_type&quot;:&quot;nav_header_wallet&quot;,&quot;tile_id&quot;:&quot;nav_header_wallet&quot;,&quot;scope&quot;:&quot;tile&quot;}</value>
      <webElementGuid>d1e72b26-31c0-4c68-b36d-e4c80cb2f09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cw_navbar__primary-item js_wallet</value>
      <webElementGuid>ca8dcd96-de86-4ec3-aa6a-a137872f69d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-av-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_loaded&quot;}</value>
      <webElementGuid>91b7f04d-2366-433f-a83d-e98228cc83b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cwt-fpti-im-sent</name>
      <type>Main</type>
      <value>{&quot;event_name&quot;:&quot;dw_nav_header_shown&quot;}</value>
      <webElementGuid>c3036422-4e7b-45c4-be5f-99d2c5fff8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02779bfc-c562-461b-83fe-72f8171e14d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wallet</value>
      <webElementGuid>79c47041-6f03-48f7-8e89-dd02111e5279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cw_root cw_navbar_enabled&quot;]/div[2]/div[@class=&quot;cw_navbar_drawer cw_drawer_closed&quot;]/div[@class=&quot;cw_navbar cw_navbar--wide&quot;]/div[@class=&quot;cw_navbar__mainnav&quot;]/nav[@class=&quot;cw_navbar__nav&quot;]/ul[@class=&quot;cw_navbar__primary&quot;]/li[3]/a[@class=&quot;cw_navbar__primary-item js_wallet&quot;]</value>
      <webElementGuid>2285cd85-961a-4a67-a0b3-aa83ac0a6def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wallet')]</value>
      <webElementGuid>1c0ecd0b-bb6a-4edd-a2ee-53c6f8c679da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim dan Minta'])[1]/following::a[1]</value>
      <webElementGuid>1f27149d-07ef-4fea-813d-c2e7542e9633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel Kontrol'])[1]/following::a[2]</value>
      <webElementGuid>95aed5a7-9a01-4e68-95e1-97b05fce82a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas'])[1]/preceding::a[1]</value>
      <webElementGuid>086d228f-33f5-421c-b8c3-6b4eca00e4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/preceding::a[2]</value>
      <webElementGuid>e50ca9e1-2037-4882-ae42-6aab356135d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wallet']/parent::*</value>
      <webElementGuid>0b7e509f-0eea-4cc8-ba6a-c31ed492ff24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/myaccount/money')]</value>
      <webElementGuid>d884107c-ad06-467f-b85e-a709c8d21198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>1a3101de-f25a-40e4-b0fb-5c2eba4233ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/myaccount/money' and (text() = 'Wallet' or . = 'Wallet')]</value>
      <webElementGuid>04e6fdf8-9b64-473e-84d1-f35848e90c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
