<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>favoriting contact 1</name>
   <tag></tag>
   <elementGuidId>bcd0a598-5409-46da-8c6c-32434e722af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#makeFavorite-PID-497T-6SMN-P5XN-E3X6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='makeFavorite-PID-497T-6SMN-P5XN-E3X6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181bc8c3-d2c7-4ba2-865f-33dc26cbfa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>makeFavorite-PID-497T-6SMN-P5XN-E3X6</value>
      <webElementGuid>45439fa5-a903-41db-bc57-85950c68793e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>favoriting</value>
      <webElementGuid>2ffd7317-aa31-42dc-8890-ab05514ef5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ebbe510c-7f5f-4dde-945d-a19dbf4f4339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ivjdcq</value>
      <webElementGuid>ccae43c6-a732-4967-b37c-7d2971eff792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;makeFavorite-PID-497T-6SMN-P5XN-E3X6&quot;)</value>
      <webElementGuid>a6ddee28-870d-49c2-be90-4846e8713e1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='makeFavorite-PID-497T-6SMN-P5XN-E3X6']</value>
      <webElementGuid>33ff9a51-9520-46c8-a598-50ca3e4b0158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/div/div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>de5c82c2-6c60-4cb5-b083-31552c093889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5ef0436e-3b32-4a3e-ae56-c8e272fe49df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'makeFavorite-PID-497T-6SMN-P5XN-E3X6' and @name = 'favoriting' and @type = 'checkbox']</value>
      <webElementGuid>d33718d6-3a50-4a4f-8009-6230756a67cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
