<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View blocked contacts</name>
   <tag></tag>
   <elementGuidId>0a801fe0-088d-451d-9fc8-a012ab10e158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-18m6lt0-links_base-text_body_strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9694a725-9e73-4498-bd29-8a78fcbcfbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18m6lt0-links_base-text_body_strong</value>
      <webElementGuid>e2d87cdc-009c-42b4-8742-6d8c015b5313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.7.1</value>
      <webElementGuid>1045a851-1dcc-458f-9a3a-5bd4438563ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ee54efc-8f60-4b87-ba28-89ecf56c5d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View blocked contacts</value>
      <webElementGuid>87c22146-f2bf-40d0-8ed0-298956faa803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper false&quot;]/div[1]/div[1]/div[@class=&quot;css-18v44rk&quot;]/div[@class=&quot;css-1wjrt09&quot;]/div[@class=&quot;css-yg8jkz&quot;]/div[@class=&quot;css-1jec218&quot;]/div[@class=&quot;css-guhnor&quot;]/button[@class=&quot;css-18m6lt0-links_base-text_body_strong&quot;]</value>
      <webElementGuid>2d1957df-6337-4e6f-8ed7-2f99d4097347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>19aecf3c-2e3d-48f9-89e5-2966801c90c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/div[2]/div/div/div/div[4]/button</value>
      <webElementGuid>31dd08cc-1336-46c4-844b-bcb4cd069130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Store'])[1]/following::button[1]</value>
      <webElementGuid>08ef54f7-797f-45b5-90e5-d9f3fb7f19cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top contacts'])[1]/following::button[1]</value>
      <webElementGuid>2b0b5c60-9f28-4b2d-945d-7edfe0c985bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get paid with your PayPal.Me'])[2]/preceding::button[1]</value>
      <webElementGuid>f1642b25-510a-4053-8563-3246d658dc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Your Link Now'])[1]/preceding::button[1]</value>
      <webElementGuid>1cd60266-158d-49f5-9cc1-eb9a8fe0e099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View blocked contacts']/parent::*</value>
      <webElementGuid>d22281e5-9459-4af1-b7b7-9997d78fb944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>73ab0217-6ba0-4908-8a4c-60939454ccb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View blocked contacts' or . = 'View blocked contacts')]</value>
      <webElementGuid>3a8ceba4-53fa-483e-9082-881210e4dab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
