<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Agreement</name>
   <tag></tag>
   <elementGuidId>817e8c84-0ff8-4a37-8519-e4e46676198b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_emailPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paypalAccountData_emailPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75db4378-43f0-4475-b4fa-6bdc8b2de40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-ylhy9c-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>edfca5a6-797f-44ae-b3f2-db64244b9207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.5.4</value>
      <webElementGuid>ef2ad029-7379-4c87-9816-891d060466e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/appData/action</value>
      <webElementGuid>1aff63d4-e410-4cb2-b315-66e8bae958cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_emailPassword</value>
      <webElementGuid>7549a432-94e7-4e29-a17f-fd4bb25e8cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>submit_account_create</value>
      <webElementGuid>f71a76fc-911c-4c7e-b489-a019a23111ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>page_submit</value>
      <webElementGuid>10306166-6126-4e93-9a57-d9a58eab243e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setuju dan Buat rekening</value>
      <webElementGuid>b07e89b4-4b29-4e13-9156-c873e3d5b446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_emailPassword&quot;)</value>
      <webElementGuid>79025988-5a8d-494f-bae4-509673a57702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paypalAccountData_emailPassword']</value>
      <webElementGuid>353172f2-7f65-4b2c-969f-f7dc79f0a607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div[9]/div/button</value>
      <webElementGuid>1873e4ff-c270-4736-b23a-6bb3f2402a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan promosi dan penawaran dari PayPal. Anda dapat mengubah pengaturan ini kapan saja.'])[1]/following::button[1]</value>
      <webElementGuid>cab9a7c7-9640-4278-84ac-032c083df3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernyataan Privasi'])[1]/following::button[1]</value>
      <webElementGuid>f55c6aad-c6fb-405f-b859-db55c59510d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2024 PayPal'])[1]/preceding::button[1]</value>
      <webElementGuid>619501f4-2d7d-4567-807c-c9cc5b84e13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privasi'])[1]/preceding::button[1]</value>
      <webElementGuid>f30930f9-87bb-4c9b-b1f0-fadeeb3ca62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Setuju dan Buat rekening']/parent::*</value>
      <webElementGuid>fe9af5a6-44af-4b9a-a9a7-c519538904c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/button</value>
      <webElementGuid>93426f22-9d14-437b-ada2-6b4c40b0597f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '/appData/action' and @id = 'paypalAccountData_emailPassword' and (text() = 'Setuju dan Buat rekening' or . = 'Setuju dan Buat rekening')]</value>
      <webElementGuid>d3eb0c5d-edf0-4219-82b7-0f61ae832a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
