<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Agreement Check</name>
   <tag></tag>
   <elementGuidId>86af9014-5d24-4f4d-b7cc-bb2d46bf40db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pp-cons-109pikv-checkmark_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='PageMainForm']/fieldset/div/div/div[7]/div/div/div/div/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93c21ff7-cfa9-4984-86d8-bf773e690863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d05383f-761a-4c2f-880b-2f46a27a110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-109pikv-checkmark_container</value>
      <webElementGuid>ede3c0da-0fb9-4871-af84-59e225ed4781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageMainForm&quot;)/fieldset[1]/div[@class=&quot;formFieldsContainer&quot;]/div[@class=&quot;pp-cons-1jdwb3y-container_form&quot;]/div[@class=&quot;pp-cons-1v26bvb-row-justify_content_center&quot;]/div[@class=&quot;pp-cons-1aqxtsc-col_form_full&quot;]/div[1]/div[@class=&quot;checkbox-tooltip-container&quot;]/div[@class=&quot;pp-cons-11m2iee-checkbox_base&quot;]/label[@class=&quot;pp-cons-12v4qsp-label-text_body&quot;]/span[@class=&quot;pp-cons-bzuo57-checkbox_items&quot;]/span[@class=&quot;pp-cons-109pikv-checkmark_container&quot;]</value>
      <webElementGuid>4f52b40c-07b6-4f16-aaa1-322c2ab2018e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div[7]/div/div/div/div/label/span/span</value>
      <webElementGuid>1ed3d1aa-e1c8-4bde-9d79-d682976812c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format kode pos tidak valid.'])[1]/following::span[2]</value>
      <webElementGuid>1a122a6f-2843-4133-aebf-6b65b6525be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Pos'])[1]/following::span[4]</value>
      <webElementGuid>6530d161-8f45-41e0-b425-8a818848bccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesepakatan Pengguna'])[1]/preceding::span[2]</value>
      <webElementGuid>4e5e6b69-d4f0-45fd-a8ff-47b2bb6a3870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>821d0964-6db7-4af2-9bb0-08f599af9efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
