<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Berbelanja</name>
   <tag></tag>
   <elementGuidId>d015bf00-fd08-48e0-b3d1-d130c2f86441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.intent-tile-redesigned.intent-card-t1.pp-cons-1ib3jfh-card_base-clickable-elevation_level1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='PageMainForm']/fieldset/div/div/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aef2975b-fdaf-4e4f-92c7-179060f528e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>intent-tile-redesigned  intent-card-t1 pp-cons-1ib3jfh-card_base-clickable-elevation_level1</value>
      <webElementGuid>225be8bb-5c74-4464-b2a7-2e83199f7419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>card_2.2.3</value>
      <webElementGuid>dd3f2627-c255-46db-9b81-3ae82e55f281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>card</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a649a84-8355-4182-8f33-f7ec85e7807a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>shop</value>
      <webElementGuid>3d01baca-271f-4436-b42f-57a4fbded2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BerbelanjaCheckout pada jutaan situs web dengan menambahkan kartu.</value>
      <webElementGuid>c15d2302-9f13-44ea-9723-a1a072531e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageMainForm&quot;)/fieldset[1]/div[@class=&quot;formFieldsContainer&quot;]/div[@class=&quot;pp-cons-1jdwb3y-container_form&quot;]/div[@class=&quot;pp-cons-1v26bvb-row-justify_content_center&quot;]/div[@class=&quot;pp-cons-1aqxtsc-col_form_full&quot;]/button[@class=&quot;intent-tile-redesigned  intent-card-t1 pp-cons-1ib3jfh-card_base-clickable-elevation_level1&quot;]</value>
      <webElementGuid>82918f1b-921c-48da-9973-e564a99b1da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div[3]/div/button</value>
      <webElementGuid>4cbd06f5-3562-4983-a583-2a392b1fc4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabunglah bersama lebih dari 400 juta orang yang menggunakan PayPal secara global.'])[1]/following::button[1]</value>
      <webElementGuid>8fc305a3-35b7-4500-b5e8-27cb398a2802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa yang ingin Anda coba terlebih dahulu?'])[1]/following::button[1]</value>
      <webElementGuid>3c86d37b-ef4c-41d6-b660-d7da6e50c56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>52463bfb-7e0f-440a-9b3b-6d63633bb923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'BerbelanjaCheckout pada jutaan situs web dengan menambahkan kartu.' or . = 'BerbelanjaCheckout pada jutaan situs web dengan menambahkan kartu.')]</value>
      <webElementGuid>3b48b663-f77a-4e5a-aec5-b216ac47b71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
