<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email</name>
   <tag></tag>
   <elementGuidId>549a61a6-3d77-43e7-8ea4-9757535dbf8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypalAccountData_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ceac294-c8de-4dcc-8803-7e79ab4ffdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>686bd1a4-bb22-4768-b75c-20beb007e2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-16mpn99-text_input_control-text_body-label_placeholder_shown_and_not_focused-text_body</value>
      <webElementGuid>27ad1b4a-105b-41e3-bfa9-f6a519fa018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/paypalAccountData/email</value>
      <webElementGuid>07bc1530-c1af-4a47-937e-3a9b3da3395b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_email</value>
      <webElementGuid>2df9c533-3d11-41a3-84f4-ed8ba23a3bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4094202-e867-4c09-be2c-2370a83932e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paypalAccountData_email-label</value>
      <webElementGuid>ebf77968-960e-4dee-9c10-71789ad20404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9c0a161a-1a14-48ce-b87d-4c80fd578232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac9228de-406e-46aa-8465-111ec502a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_email&quot;)</value>
      <webElementGuid>e80829df-43b9-43f4-9e3a-33d34cec70c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypalAccountData_email']</value>
      <webElementGuid>2f873972-a5da-4a9b-ac69-865f401fe5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>0e5a74c4-94f9-464c-b4fb-ebc5dc29a84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e0c31a5d-1a3a-4834-a807-db149d4e6f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = '/paypalAccountData/email' and @id = 'paypalAccountData_email']</value>
      <webElementGuid>d6be6ba9-a8ba-4016-8e24-a133a51a7fc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
