<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First Name</name>
   <tag></tag>
   <elementGuidId>321116cd-1f78-49af-ae28-fa0f043852fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_firstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypalAccountData_firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ab9041f-98fb-4820-9c45-f6eb1ebb170e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-16mpn99-text_input_control-text_body-label_placeholder_shown_and_not_focused-text_body</value>
      <webElementGuid>0ce5d02a-fe45-425c-9344-c423f99adbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/paypalAccountData/firstName</value>
      <webElementGuid>0880d0d6-65d7-4e91-9f3b-451525de0e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_firstName</value>
      <webElementGuid>6c6942b1-2903-4c60-8ea6-5c5a38491cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a29b88e4-2324-4e91-b44a-8b2f4d5b1099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paypalAccountData_firstName-label</value>
      <webElementGuid>318b680f-ce12-4ded-8e47-464295f42e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdce1a97-a67b-4da9-aa8d-2876c2a9cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>c342c707-d64c-42df-af81-d580382e8206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1b064c9-f7f4-4a53-b997-ab89abd0b541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_firstName&quot;)</value>
      <webElementGuid>f22e68bc-b02e-4402-add6-295fcfcbb1bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypalAccountData_firstName']</value>
      <webElementGuid>31013d2a-6d25-4b3d-bf2e-8ac2c2f69245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>190c2fc8-1cca-403d-b84f-242b7a9f5b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fa06d378-976a-4f13-853d-233bbd8e359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '/paypalAccountData/firstName' and @id = 'paypalAccountData_firstName' and @type = 'text']</value>
      <webElementGuid>2e9340cf-f884-440e-a608-68c7b59479dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
