<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Indonesia</name>
   <tag></tag>
   <elementGuidId>cbd80d48-5b8d-4d4e-b673-ddff55004623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuButton_paypalAccountData_nationality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuButton_paypalAccountData_nationality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cea2fd26-87bf-4ba3-8ee0-5d849fb14f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-ih2vqh-dropdown_menu_button-text_field_value_sm-active</value>
      <webElementGuid>db6132da-0176-4950-a2af-35f0260202bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b368910-52c7-4272-8674-41b430e2cc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton_paypalAccountData_nationality</value>
      <webElementGuid>2e7dc973-0494-4f31-aee7-4b6d6a790e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d6ea9fa7-3803-4847-a5f6-4deadaef12d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58f07bc2-f01e-4b7a-8701-2713d22a29e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dropdownMenuButton_paypalAccountData_nationality-label dropdownMenuButton_paypalAccountData_nationality</value>
      <webElementGuid>ef39557f-a2fb-4909-9254-b50444a942a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>117646f8-da36-477e-87ac-8196d321aaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>paypalAccountData_nationality</value>
      <webElementGuid>a4136b05-6e10-4c17-97f3-972324bb7eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1947fb3c-3e7c-4154-9144-a4ec743406f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45da2bb2-3969-4bd6-8607-0bed9e1b90f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>f918d0ef-6b9a-4db9-b008-5ce372011498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuButton_paypalAccountData_nationality&quot;)</value>
      <webElementGuid>1b548e65-e34d-44ba-839e-0f7b531185f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuButton_paypalAccountData_nationality']</value>
      <webElementGuid>e6e07d72-2aae-4825-a02c-48cd636c2f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paypalAccountData_nationality']/button</value>
      <webElementGuid>b129aa52-fde5-4ab2-9c2f-07743a5af02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pastikan informasi ini sesuai dengan ID resmi Anda.'])[1]/following::button[1]</value>
      <webElementGuid>b63d57f9-5b46-44e3-85ee-bfb1af932bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi pribadi'])[1]/following::button[1]</value>
      <webElementGuid>0cb7b360-e40d-41d3-adab-c52251d09a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewarganegaraan'])[2]/preceding::button[1]</value>
      <webElementGuid>52d2e7f7-a04e-4f1d-8ab8-713e07b0498d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>bb861bf0-37e6-4b77-832c-4036ab18f5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenuButton_paypalAccountData_nationality' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>054c941c-06da-4993-9e0d-8d42f3520ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
