<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input ID</name>
   <tag></tag>
   <elementGuidId>476cacf8-6a84-45e1-b73f-b75bccb7a4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_identificationNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypalAccountData_identificationNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9740de4f-5a36-4c9f-9dfc-0fcd81835386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-16mpn99-text_input_control-text_body-label_placeholder_shown_and_not_focused-text_body</value>
      <webElementGuid>28b772e0-211e-4c5c-89f2-037017f4f706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/paypalAccountData/identificationNumber</value>
      <webElementGuid>c3fd7cb1-6623-43fe-8d16-7f1601a41a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_identificationNum</value>
      <webElementGuid>e15e75d6-c0da-446b-82f5-43668d5e7376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aca9c2d8-4beb-440d-8c0f-dd5c6b65dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paypalAccountData_identificationNum-label</value>
      <webElementGuid>579f1b60-3698-4105-83a0-753429d36e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8a95163-c9d6-457e-946d-acabb27d7ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0322fcb3-0258-46d0-8231-e27e01f919f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>cddd4173-7cdc-4750-be27-f262a64bc9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ad2f03c-cb5f-44cf-bc27-b1992fd894b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>13123213</value>
      <webElementGuid>c166d694-0d10-41a8-99a9-4475a3eb4d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_identificationNum&quot;)</value>
      <webElementGuid>5e5e0f8e-cf5b-44e4-a732-1601cbe49684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypalAccountData_identificationNum']</value>
      <webElementGuid>f21efcff-3bc1-4f56-a701-42875efb303d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>02e9d8ef-0ef2-450d-999f-2dcaddf9bd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>531a4b56-4978-4a3b-a27d-2065a4d9a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '/paypalAccountData/identificationNumber' and @id = 'paypalAccountData_identificationNum' and @type = 'text']</value>
      <webElementGuid>586c7e0c-5913-4d67-8615-a949ee178007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
