<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no telepon</name>
   <tag></tag>
   <elementGuidId>850fb22d-471b-47b7-9ad8-702e9b5b4ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypalAccountData_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d663187-fc68-4473-bdb8-6856a8bdf089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-cons-u85qw5-text_input_control-text_body-label_placeholder_shown_and_not_focused-text_body-prefix_wrapper_control-prefix_wrapper_control_with_prefix</value>
      <webElementGuid>520851fb-5ebf-4817-9aa2-f6b8d81dee68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/paypalAccountData/phoneNumber</value>
      <webElementGuid>6008cec6-ace7-48c6-9fb2-f1635f235c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_phone</value>
      <webElementGuid>77344300-40b8-4215-ae0e-25ec70521fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>610dc233-6b48-49f6-a540-3507e2647ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>paypalAccountData_phone-label</value>
      <webElementGuid>abbea160-0f37-4661-a607-31aec42819d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>14c494e0-7508-4698-aa94-ecba601789ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>ed52a634-3f7d-4f39-aa79-60d2f2562355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8cebb1ad-b8ea-4cbd-841f-d12154e73e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>961653ec-2b94-4622-b537-7ee1602a5dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_phone&quot;)</value>
      <webElementGuid>ca295972-2c8d-43f6-a391-303c9c4e6ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypalAccountData_phone']</value>
      <webElementGuid>287cbb2d-6cd7-4084-88b9-5b5c3854dcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>28212bac-ecdf-461e-8561-293d7dc3c7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d16e0095-fa5c-4efc-b361-a57ecc31356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '/paypalAccountData/phoneNumber' and @id = 'paypalAccountData_phone' and @type = 'tel']</value>
      <webElementGuid>88cb93d6-70e7-40e7-b58c-1ee3cb2ec24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
