<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skip</name>
   <tag></tag>
   <elementGuidId>61af74cb-b089-4ebf-a4aa-80234336da94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalAccountData_notNow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='paypalAccountData_notNow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51c6707b-f15f-48fa-a5a4-160066c13684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn vx_btn vx_btn-secondary vx_btn-medium pp-cons-1lrqnhe-links_base-text_body_strong</value>
      <webElementGuid>174b5b1e-9369-4e33-b0f8-cfc4b7c9da16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>links_4.6.4</value>
      <webElementGuid>c405c8f7-3423-4cf8-8c3a-1c98025bd5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>261da0dd-683e-400e-b9ac-e36ef58a9c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer noopener</value>
      <webElementGuid>87a72e38-27ec-45b3-9b89-c66ed42204a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>not-now</value>
      <webElementGuid>dd024efb-5a5b-4cf3-a17b-6f792360e1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>2327eafe-3b80-47e0-8b56-c1b135d3ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalAccountData_notNow</value>
      <webElementGuid>2caaf2d9-27ba-49ff-95c0-fa6f0367f85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c1245cf2-ed03-4f94-8779-327b4d024dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jangan sekarang</value>
      <webElementGuid>591ca320-18af-4a74-9b06-aa70764d039c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalAccountData_notNow&quot;)</value>
      <webElementGuid>4a2be231-b408-4d9a-924c-86cf6a11e5e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='paypalAccountData_notNow']</value>
      <webElementGuid>bb1e042f-ed3e-4284-b0cc-0f0bbb5a1247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageMainForm']/fieldset/div/div/div[6]/div/a</value>
      <webElementGuid>d18f53f2-e248-46df-906f-e30c9394f553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jangan sekarang')]</value>
      <webElementGuid>f910df8f-0e74-4926-a527-b7e7ee09f3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengirim pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>63f1c3a1-ba75-49dd-aacb-63d21ff7ff85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='©2024 PayPal'])[1]/preceding::a[1]</value>
      <webElementGuid>660ab0f9-07f4-49d6-adad-e973c721164f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privasi'])[1]/preceding::a[1]</value>
      <webElementGuid>30b2997d-cfd0-4ac8-afa6-96f20c5a1b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jangan sekarang']/parent::*</value>
      <webElementGuid>1f056254-71e9-43af-aab5-6d0579cea935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>9c398c93-bf7a-4515-9b8c-d13d6911ad2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f8089df4-ff57-4747-8314-dbcb5f1f7786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'paypalAccountData_notNow' and @href = '#' and (text() = 'Jangan sekarang' or . = 'Jangan sekarang')]</value>
      <webElementGuid>57b9236a-ece6-4a4d-985b-79c5026b4893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
