<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirmation Invoice</name>
   <tag></tag>
   <elementGuidId>7eff6c21-8103-44d1-8199-046aa2454125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pp-react-styles-fqf01p-alert_base-text_body-success-no_close_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='desktop-page']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d40516dd-fc6b-4c6b-bd80-2e3f3d0a0fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>65cb761f-f7f8-4b25-b9c6-aea369a4adc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-react-styles-fqf01p-alert_base-text_body-success-no_close_btn</value>
      <webElementGuid>67f47526-0290-4959-a653-6804633afe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>alert_3.4.8</value>
      <webElementGuid>ff3bc87b-e618-4907-9b9d-544ad4e07298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your invoice to receiver-payment@personal.example.com has been sent.</value>
      <webElementGuid>541e56b2-40cd-4bde-9e60-6f96e675057f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-page&quot;)/div[@class=&quot;dashboard-container&quot;]/div[1]/div[@class=&quot;pp-react-styles-fqf01p-alert_base-text_body-success-no_close_btn&quot;]</value>
      <webElementGuid>3f1a4ad5-9961-4e13-882f-87ffde487aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktop-page']/div[2]/div/div</value>
      <webElementGuid>1b71b27c-01b0-4ad2-a58d-721fa6b5a334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::div[3]</value>
      <webElementGuid>0e8f609d-20e0-4b75-ac9c-61f1589ab4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Messages'])[2]/following::div[6]</value>
      <webElementGuid>2ed09807-4316-4bf1-8664-00e7d7a01820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoicing'])[1]/preceding::div[1]</value>
      <webElementGuid>16c855c2-bcd9-4de0-98c2-445110819d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Invoice'])[1]/preceding::div[2]</value>
      <webElementGuid>297c6768-fb70-4ec0-989e-1e10b94626e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your invoice to receiver-payment@personal.example.com has been sent.']/parent::*</value>
      <webElementGuid>b4e930c8-bd67-43fc-82cb-35f3a1693950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>27e13d04-1ccb-42b7-9992-96e6d60fd958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your invoice to receiver-payment@personal.example.com has been sent.' or . = 'Your invoice to receiver-payment@personal.example.com has been sent.')]</value>
      <webElementGuid>aa56d96e-358a-40e2-ac7b-4906badd1c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
