<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Invoice</name>
   <tag></tag>
   <elementGuidId>49066973-d898-4173-ba53-743c342b0960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action-btn-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='action-btn-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10b344d9-fb0a-4bde-b6b4-47e82443e8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>915e783a-f4be-488a-b06b-db17216548a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-button pp-react-styles-c72rwi-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>4292c0e7-fff3-4a45-b77d-169318098e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.1</value>
      <webElementGuid>3679b338-17a7-4d94-8c2f-72dfb44b5598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-btn-4</value>
      <webElementGuid>0c57a95f-a06b-4d47-8292-3a18f26795cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>action-button</value>
      <webElementGuid>54891e76-139d-430d-8c71-591a3d295a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>primary-action-btn</value>
      <webElementGuid>73feb5f6-43cc-4e37-a014-1a3faddcb310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>860a56a3-3f73-4cbc-8125-af3f20bf5811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Invoice</value>
      <webElementGuid>9a4b2a74-bbb1-47be-940b-187ae0c96a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-btn-4&quot;)</value>
      <webElementGuid>b806f3db-7815-46b0-84ca-540cc9e5fa20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='action-btn-4']</value>
      <webElementGuid>1be99549-05c1-48bd-b239-e6068769950c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-and-actions']/div[2]/span[3]/button</value>
      <webElementGuid>7d159fed-fe92-4a50-90f5-2d428fbc0d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoicing'])[1]/following::button[3]</value>
      <webElementGuid>ab18921d-55bf-4daa-b9c2-2361cc51768d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::button[3]</value>
      <webElementGuid>94aa1dd3-e623-40ff-a955-35aea82e0225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[1]/preceding::button[1]</value>
      <webElementGuid>8ce1f2cc-cb4e-4878-8b5a-49cd2e796e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimates'])[1]/preceding::button[2]</value>
      <webElementGuid>2d74afa8-2634-4e34-9b31-91dcd475c7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Invoice']/parent::*</value>
      <webElementGuid>0ba2baa5-5cd6-4fc6-8b82-d1cfcc9a2285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/button</value>
      <webElementGuid>a83dba3f-9757-41c6-8cf4-4c482a56f942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'action-btn-4' and (text() = 'Create Invoice' or . = 'Create Invoice')]</value>
      <webElementGuid>3c761729-d99f-45e8-a849-c563738cdb69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
