<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>due in 10 days</name>
   <tag></tag>
   <elementGuidId>dd8cd969-385e-4091-94cf-d5827cb69ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#smenu_item_NET_10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='smenu_item_NET_10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b93ae8fa-5404-4b6a-9ac8-8decf9607810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-react-styles-rsd463-list_item</value>
      <webElementGuid>a803f76f-243a-4681-baa4-e8f294e99db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>smenu_item_NET_10</value>
      <webElementGuid>a19fa01d-546f-4de1-a1a1-9418b96783ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>af9d86c2-5c79-4f00-b218-b8431f2479d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ca91258-4d2e-4070-b533-920cb3542af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ccfc0160-cfb6-4c42-af42-f287ab389de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>NET_10</value>
      <webElementGuid>afee1e54-9235-454b-b345-8a91a4ae93b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>954febf4-d92a-4f1a-8870-8ab74532670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In 10 days</value>
      <webElementGuid>c97a369b-e86b-4cb1-845f-2d07f84ff9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smenu_item_NET_10&quot;)</value>
      <webElementGuid>64be6e14-7568-482c-8fc1-e3db03838b3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='smenu_item_NET_10']</value>
      <webElementGuid>166309e3-01f1-413d-9156-1291b66990d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='selectionMenu_263']/li[4]</value>
      <webElementGuid>87eb915c-8d56-4e56-81a4-d6ade490390b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On specific date'])[2]/following::li[1]</value>
      <webElementGuid>bc50d5af-1b8e-49db-8d66-f6cb6aedabf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No due date'])[2]/following::li[2]</value>
      <webElementGuid>8c49b1c8-9f6c-483e-9a45-6c042aeb8d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In 15 days'])[2]/preceding::li[1]</value>
      <webElementGuid>7179de27-0073-4ff9-8be8-385b1ddf6a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]</value>
      <webElementGuid>d4f6bee3-62d9-46ae-a358-a2eeb36c54b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'smenu_item_NET_10' and (text() = 'In 10 days' or . = 'In 10 days')]</value>
      <webElementGuid>fe2bd1ce-aff2-454b-b835-b23e2e71d776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
