<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input email</name>
   <tag></tag>
   <elementGuidId>3825d0b6-a436-4603-a462-9a543a5f08b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo_txt_recipient-input-combobox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combo_txt_recipient-input-combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0310d07b-d49b-4d4e-abd0-18125c783cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-react-styles-1sejdtu-text_input_control-text_body-text_input_control_with_icon_right-label_placeholder_shown_and_not_focused-text_body</value>
      <webElementGuid>01d6efde-9f88-4b85-b5fd-eb790efc9c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo_t_email-input</value>
      <webElementGuid>b7d25d3b-aace-4813-8ae1-378cf919aa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo_txt_recipient-input-combobox</value>
      <webElementGuid>e08a3826-ae0c-4694-b75d-72d87fb53a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7dafff22-f119-4036-ab58-07df51b36c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>v2</value>
      <webElementGuid>49a40a0e-56aa-4ed9-a1dd-53c3f97a7d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>05ffdb32-cade-4259-bad0-2e1ae27f08a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84bd6285-9304-4769-b1a8-0de588bf8dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0ea7f4d1-6e01-46ed-9924-aba4ccdecd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de9d7c9c-6dfc-4a26-aeea-3c1484ab453c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>combo_menu_recipient-input-combobox</value>
      <webElementGuid>e4b807b9-6748-44b8-aebd-bb3d27ca92e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactcombo</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff5ebe9b-65d3-4f60-b1e3-87aebedb250d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc3cd046-4ea7-494e-a3bc-b516086d54d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo_txt_recipient-input-combobox&quot;)</value>
      <webElementGuid>cc8aa727-6ac5-4790-9e1c-c6dc003595a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combo_txt_recipient-input-combobox']</value>
      <webElementGuid>986fc405-627a-4bde-a0d5-eb0266ee10eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktop-page']/div[3]/div/div/div/div[2]/div[3]/div/div/div/div/input</value>
      <webElementGuid>10f40a2c-5022-418e-bbfd-d982ba0c226d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8bd503b9-431f-47a2-8840-8d0c673cc18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'combo_t_email-input' and @id = 'combo_txt_recipient-input-combobox']</value>
      <webElementGuid>4c436569-1a1a-4c65-aa3c-b930e5b6d4b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
