<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item computer</name>
   <tag></tag>
   <elementGuidId>2a2ce3af-a460-4a5c-b21d-2f574d8e6189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ITEM-88A789506S228030W</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ITEM-88A789506S228030W']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d19bf941-d499-4571-b5cd-6ebc4078296a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-react-styles-rsd463-list_item</value>
      <webElementGuid>3cac0ad4-0038-4ed3-b4a9-7ee4a3626d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ITEM-88A789506S228030W</value>
      <webElementGuid>85c4777e-e950-4b5a-adc7-c4288f1bad28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>894d4e37-b5d1-443b-9e38-d20676230e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fd9b616-6cdf-4d8c-83ad-0ca9b37211f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>081f3e1a-7d9d-4721-bc52-82a9c1e2a85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Computer</value>
      <webElementGuid>f9ae3d11-dcce-4c0a-82a3-c47cf9bd803d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8fa031c6-e23d-4637-9e31-98580119873f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ComputerRate 5000.00</value>
      <webElementGuid>fa4932b4-6f23-4ea7-8137-860e70b6bedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ITEM-88A789506S228030W&quot;)</value>
      <webElementGuid>1877c127-4b92-48b7-ae18-1ba97487d33f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ITEM-88A789506S228030W']</value>
      <webElementGuid>1a000c37-e2ca-4c26-a87b-ff430a985a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='combo_menu_combobox_item_0']/li[2]</value>
      <webElementGuid>ca0c3fe3-d0d0-4eb3-84de-34605b67adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new item'])[1]/following::li[1]</value>
      <webElementGuid>b506c6ef-0c8f-4714-a9a6-30f183fa0e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item name'])[2]/following::li[2]</value>
      <webElementGuid>83edea45-7ae4-4d78-8229-7d47f6987f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]</value>
      <webElementGuid>10e4d857-400f-4e8c-8417-d71faaf4db46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ITEM-88A789506S228030W' and (text() = 'ComputerRate 5000.00' or . = 'ComputerRate 5000.00')]</value>
      <webElementGuid>4b640f23-f481-467e-aff1-2383a2297aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
