<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message to customer</name>
   <tag></tag>
   <elementGuidId>e2cc9217-0550-48a2-b375-a025a7120be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='text-input-note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6b1b5d09-41c9-40fc-99c2-f8c3cb38da9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pp-react-styles-ltf7uk-text_input_control-text_body-label_placeholder_shown_and_not_focused-text_body-text_area_control</value>
      <webElementGuid>252b8af0-cae7-4a0a-a9c0-ab91d277b5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>d58cc81d-e3ed-45f4-a67c-56293ff422e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-note</value>
      <webElementGuid>67fbe0c9-73a8-466b-a45f-8d9955f1e9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32635c18-5360-472e-8aa9-4a63987e6098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>text-area_5.5.4</value>
      <webElementGuid>319e5f7f-57e3-4014-82b9-d3fbfa29db0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxlen</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>96dcaef1-6608-414c-a2bf-a34f8eeedcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f704d83-61c6-4861-8ff3-aeea199f9aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-note&quot;)</value>
      <webElementGuid>97bd7334-3db5-4329-bb57-55da6931bc53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='text-input-note']</value>
      <webElementGuid>8b9ada31-cc2f-43f4-80bf-d0683da9c807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notes-section']/div[2]/div/div/textarea</value>
      <webElementGuid>71f317e8-9424-4da5-b9d4-70c0d6c8008c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/textarea</value>
      <webElementGuid>fbc0f0a3-b2e4-4f4c-b28f-c710d07b5b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'note' and @id = 'text-input-note']</value>
      <webElementGuid>7af2f155-8601-4cc8-83a2-ddf9fb676f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
