<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send</name>
   <tag></tag>
   <elementGuidId>c11b75df-993e-48e5-97f8-5f015cc50b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action-btn-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='action-btn-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2088101a-39b4-4344-adfa-adc4d73a2df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>876a2045-7225-49e1-b32f-667fd3f2a794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-button pp-react-styles-c72rwi-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>d1301238-387a-4fd8-b21e-bb9f4544322f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.1</value>
      <webElementGuid>aba6ff33-f27a-4632-a73f-1ea1822d0fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-btn-3</value>
      <webElementGuid>0389f23c-bd0f-4759-93de-0704fc9d33fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>action-button</value>
      <webElementGuid>7d0f57c3-5325-470c-ae6d-0662ea39d448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>primary-action-btn</value>
      <webElementGuid>0b54f8dc-e205-4459-a5fd-9b320aba423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ccccf51b-aa31-4f1a-885b-af7d49cab949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>ee64f514-cb30-4e7b-8713-bf35321df504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-btn-3&quot;)</value>
      <webElementGuid>809c9c0a-dbc1-4355-b35f-5d74d5de9e74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='action-btn-3']</value>
      <webElementGuid>9c63a3e4-53fa-4cd3-96bb-d5f76f37df83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-and-actions']/div[2]/span[3]/button</value>
      <webElementGuid>ddac1199-a991-4cba-bac2-7a54f6b51152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice #(0001)'])[1]/following::button[3]</value>
      <webElementGuid>5652b2c7-2065-44af-acf1-d666c00c4359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::button[3]</value>
      <webElementGuid>8d88f3ad-a71e-4230-855a-be5468303303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/preceding::button[1]</value>
      <webElementGuid>e29cce4b-09fe-4220-a3cb-e02ca9ddab05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[2]/preceding::button[2]</value>
      <webElementGuid>0b5f5719-d9bd-48d8-ab9d-5b034428e23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>b2f309a6-e010-499c-8127-e8e6aad644fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/button</value>
      <webElementGuid>4d1b75c4-1b98-49c5-bf9a-7214cb8a4ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'action-btn-3' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>368ded68-e3eb-4e16-99dc-3d2fc96e8bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
