<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Log In</name>
   <tag></tag>
   <elementGuidId>39cac516-0058-44f8-933f-84eb33eb3e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_ul-btn_wrj2o_1337</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_ul-btn_wrj2o_1337']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b3d29a3-4c2e-40f0-85b8-1f2fd6c0b821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin</value>
      <webElementGuid>2c87fae6-9390-4367-8bb6-132a2b7e7285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>957ae9fc-b664-4133-87e0-b7d18cdea469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_ul-btn_wrj2o_1337</value>
      <webElementGuid>a807c36c-aec9-4401-95a6-561a88b9587e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_pypl-btn_1q7vs_1 undefined _pypl-btn--outline-blue_1q7vs_52 _pypl-btn--small_1q7vs_34</value>
      <webElementGuid>6c00496e-1b7e-465e-8240-44679a857fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu0-Cta-Log In&quot;,&quot;event_name&quot;:&quot;ppcom_header_login_clicked&quot;}</value>
      <webElementGuid>8f794f06-abaa-4051-bbc8-ca2924e1e5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff9924a4-2aeb-4c36-87b0-03c08889d867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cdcdc568-5558-4da3-9ceb-0aac90c888b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>6db2437d-8440-42a9-b716-9f1e96aa3ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ul-btn_wrj2o_1337&quot;)</value>
      <webElementGuid>7129c188-c348-45c5-8cb7-97f5ba7f0cf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_ul-btn_wrj2o_1337']</value>
      <webElementGuid>32fcc805-2bc0-4259-9a21-aab34861da14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_header-buttons_wrj2o_1146']/div/a</value>
      <webElementGuid>733708ff-3395-4049-88ee-a90b7db41a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In')]</value>
      <webElementGuid>ca0c0bdb-5092-40f6-a3c7-2de2d07b0c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>ca254250-fb44-4164-85fa-f6ae34ae4c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal Logo'])[1]/following::a[2]</value>
      <webElementGuid>674e25a6-a5c1-4cad-8ac3-fc1e2b8fd270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/preceding::a[1]</value>
      <webElementGuid>90837e0e-d5d6-4fa0-9275-94e93f86086a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JADI LUAR BIASA DENGAN PAYPAL'])[1]/preceding::a[2]</value>
      <webElementGuid>668da887-556c-4900-92de-3f21023f8e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>53c46767-57b5-4387-ad3d-0da48abd0073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/signin')]</value>
      <webElementGuid>f22060ae-32ab-446b-9881-17d8450e2694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>4ce826dd-b2a6-4211-a0a9-bb5c20194a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin' and @id = '_ul-btn_wrj2o_1337' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>37ebd875-a107-4f38-8ece-04dafc14be6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
