<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sign Up</name>
   <tag></tag>
   <elementGuidId>d673ba85-2183-4f27-8548-fd712a073181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_signup-button_wrj2o_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_signup-button_wrj2o_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b94a9f8-1f15-4439-b571-e38d6e6e5a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webapps/mpp/account-selection</value>
      <webElementGuid>8750b125-7c3e-4840-b7fd-8ee8b1a23e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>613b0ace-87d7-4900-b5cf-9b2f63e3f30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_signup-button_wrj2o_1</value>
      <webElementGuid>c0bee503-1cd6-4082-91a5-a3d7f86750b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_pypl-btn_1q7vs_1 undefined _pypl-btn--small_1q7vs_34 _sublistMobile_wrj2o_1175</value>
      <webElementGuid>437463f1-7f49-4a88-badf-4ee204e6c003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu1-Cta-Sign Up&quot;,&quot;event_name&quot;:&quot;ppcom_header_signup_clicked&quot;}</value>
      <webElementGuid>49af3dbd-5d4d-4eec-b093-80a02ee16078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f27ae567-e702-4d3e-9700-78fd82a765bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ebea926-a0c5-4665-8474-4d7bf7922f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>383f74ff-e9f1-47b5-bdb8-821ba195c556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_signup-button_wrj2o_1&quot;)</value>
      <webElementGuid>8187c75e-47b7-448f-ab94-61b11f6e7497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_signup-button_wrj2o_1']</value>
      <webElementGuid>7df53e19-b46c-4b7e-852c-ef0172840510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_header-buttons_wrj2o_1146']/div/a[2]</value>
      <webElementGuid>5071910a-2f50-4de8-a004-e7747d3844b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign Up')])[2]</value>
      <webElementGuid>0f013b50-1bf0-4ce1-ad1f-5118331ce2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::a[1]</value>
      <webElementGuid>01013b26-9539-4016-8635-4ec36b315e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[2]</value>
      <webElementGuid>276d674a-366b-469e-9405-8ba85b8f81bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JADI LUAR BIASA DENGAN PAYPAL'])[1]/preceding::a[1]</value>
      <webElementGuid>a3abd4b9-6908-4220-85d7-450be94f2927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/preceding::a[1]</value>
      <webElementGuid>b1cb0c49-0463-42ef-9d70-d2e5acd1b1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webapps/mpp/account-selection')])[2]</value>
      <webElementGuid>24caa5bc-f143-4782-8416-26eee8e686b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c1db9da8-560d-42a6-8111-db3c4322a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webapps/mpp/account-selection' and @id = '_signup-button_wrj2o_1' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>b0fd4c54-b3e6-4a0f-9f28-574562209dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
