<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Date Last 90 days</name>
   <tag></tag>
   <elementGuidId>13e8c8fe-3120-44d4-802d-1cbaa2ea7612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dateFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01b57692-de29-4230-89a9-700da9bac57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-11-6 ppvx_btn--size_sm___5-11-6 ppvx_btn--secondary___5-11-6 ppvx--v2___5-11-6 VBt1k yJXKe t2WbA filterButtonV3 dateFilterV3</value>
      <webElementGuid>134a6cc2-44b6-4ebf-afde-298588cb4557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84570134-2ee5-4801-8ed6-d859eddbb1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateFilter</value>
      <webElementGuid>2f50367d-1625-4fe8-98a1-f3a35b7f33df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>date-filter</value>
      <webElementGuid>3211d94c-0d04-4d28-8ca7-51cac989307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>dateFilter</value>
      <webElementGuid>d114d237-47df-4a3e-9c46-280967052793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3d8573f-61ee-400e-a22d-aa8405d816f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date: Last 90 days</value>
      <webElementGuid>23af1b61-8d3d-498d-8303-b16e12652881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateFilter&quot;)</value>
      <webElementGuid>fe0c8107-27e5-4181-965e-f7282ddd8eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dateFilter']</value>
      <webElementGuid>ed329798-c051-42ea-ac0b-04939836e77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/ul/li/button</value>
      <webElementGuid>73575e3b-e97a-4890-9700-cec14c226709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by'])[1]/following::button[1]</value>
      <webElementGuid>399ececd-daf5-4a54-8377-9210996ab671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by name or email'])[1]/following::button[2]</value>
      <webElementGuid>68b8f507-ec19-4910-9239-6a1cdfd7e2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/preceding::button[1]</value>
      <webElementGuid>d87ea7d0-decd-401b-8295-08deefe18965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::button[2]</value>
      <webElementGuid>eefe0aa9-83d6-4bc1-9b6f-bb49c842508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Date']/parent::*</value>
      <webElementGuid>334a948f-875d-4f5b-8d4a-857f555c5e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/button</value>
      <webElementGuid>4b7697e3-7fc2-41c0-98bd-5428da6257b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dateFilter' and (text() = 'Date: Last 90 days' or . = 'Date: Last 90 days')]</value>
      <webElementGuid>01658901-f92e-4fee-ab0e-85aa881cfcc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
