<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rangeEnd</name>
   <tag></tag>
   <elementGuidId>c025a00d-c75e-4029-9f64-9d44838cb690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-rangeEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-rangeEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b517d2df-9c3d-4df7-b43d-8fdc94171d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-13-12 ppvx_text-input__control--icon-right___3-13-12 focus-visible</value>
      <webElementGuid>ab731ac8-8f62-4ec3-bfc7-391c27a5f5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rangeEnd</value>
      <webElementGuid>d7acf57e-a53e-44de-b474-1fb93165e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-rangeEnd</value>
      <webElementGuid>dc73b63e-df1b-4a98-88c5-6d6d029ca446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f560959c-3e01-44b0-b1ec-f5592d78d9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>633fab78-4a94-41ff-b66f-afb99a1b8079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200924</value>
      <webElementGuid>ea311416-abaa-46c1-9c79-aec103355282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-rangeEnd&quot;)</value>
      <webElementGuid>a54cec55-616f-484c-9276-b3af03825ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-rangeEnd']</value>
      <webElementGuid>3adf8ff3-6ffa-43f4-b543-4523c15b6ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/ul/li/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>58d1584e-76a3-42d8-af6e-619b00f9f43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c95500f3-c644-46e6-917f-e16d31270068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rangeEnd' and @id = 'text-input-rangeEnd']</value>
      <webElementGuid>28ae15c2-5771-4dc3-86d0-2a635d7d52c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
