<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rangeStart</name>
   <tag></tag>
   <elementGuidId>a9820417-bc2f-4766-85ab-8b3980e8bc4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-rangeStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-rangeStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb678ef5-bc5f-4f30-9a3a-3eccccd13510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-13-12 ppvx_text-input__control--icon-right___3-13-12 focus-visible</value>
      <webElementGuid>013c0cee-3874-4e48-b8dd-8e491117f835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rangeStart</value>
      <webElementGuid>66a78a7c-a2d2-4e97-8b1a-6c5f728a46a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-rangeStart</value>
      <webElementGuid>a2289ef3-bceb-4c3d-b104-1f8a857a0589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1a78bee-22b5-430e-afde-286628573046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>1031df6c-ffc2-4d41-a1bd-d0cd7f931511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>010124</value>
      <webElementGuid>21288105-200a-470d-aa36-6e4da12d5447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-rangeStart&quot;)</value>
      <webElementGuid>8fb1e3ef-234a-4316-9e67-e4e4aa800c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-rangeStart']</value>
      <webElementGuid>fc76e1c3-02a2-4821-a0ae-ffa4055690fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/ul/li/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ffd0c7d5-c7df-4073-91bf-3b0f6743549c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>862203b4-3c2b-4bed-b305-b16fa3e2268e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rangeStart' and @id = 'text-input-rangeStart']</value>
      <webElementGuid>96ab9304-94df-4681-9781-205766efae2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
