<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Type</name>
   <tag></tag>
   <elementGuidId>03c268a6-a522-48b7-aba0-9edd1f5356d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typeFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='typeFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0871c248-0f20-4531-ac65-93aab0bc6ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-11-6 ppvx_btn--size_sm___5-11-6 ppvx_btn--secondary___5-11-6 ppvx--v2___5-11-6 VBt1k yJXKe _9Dnjn
					filterBtnCloseNotSelectedV3 filterButtonV3</value>
      <webElementGuid>ba9199fa-560f-49b2-9af5-19f6e652916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05af1ed2-ccd5-4a76-80f8-2d5b23a96da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeFilter</value>
      <webElementGuid>83920ebe-7405-434b-a7af-1a18e39d07f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>typeFilter</value>
      <webElementGuid>cc10f23f-a319-4616-9db1-5d14c661e482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>75076875-34a8-487d-8bf2-8fc2c0c64cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>f7a96a33-d9c1-427a-a648-ca4a7802e002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeFilter&quot;)</value>
      <webElementGuid>4e0d3263-702f-4f68-ba04-f15c9b4cc711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='typeFilter']</value>
      <webElementGuid>c592658f-d80a-4098-a814-1f8bda504a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/ul/li[2]/button</value>
      <webElementGuid>4c7b9719-1822-457e-9b6c-5d101b267e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by'])[1]/following::button[2]</value>
      <webElementGuid>a8f41921-2806-4fdf-a83a-4c2d18f33a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::button[1]</value>
      <webElementGuid>430e34d7-e72b-4a4d-9ec3-9684633635fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::button[2]</value>
      <webElementGuid>6fe045f1-fe6a-44ee-b37c-40c4e30b15b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Type']/parent::*</value>
      <webElementGuid>3cdfe132-f45e-41aa-b6fb-adf0bcf6d00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>acba9fa6-dc28-43b0-8e2d-a73150245ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'typeFilter' and (text() = 'Type' or . = 'Type')]</value>
      <webElementGuid>f6ad72cb-2b5b-47d2-ab11-805b7433e566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
